### ISSUE TITLE
fan running all the time

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#100]
I'm sorry to ask this question again, you already answered this before, but I can't find the thread. 

I've got an issue with the computer fan running all the time. You explained how I could change that but I just can't remember how, or where. Can you explain again please. 

Thanks in advance.

**Comment by Qirky** [comment]
Unfortunately that won't make a difference. The `Clock.sleep_time` doesn't relate to tempo as it is a value in seconds. If 1/16 is the shortest duration possible at 120bpm then the shortest duration at 180bpm would be 1.5/16 (180 =1.5 x 120).

**Comment by joesh1** [comment]
Okay, it was just an idea. I understand, it was really the theory that if one hears (thinks of) the beat as 1/8th notes, rather than 1/4 notes, then it changes the person:coder's concept of time and 1/8th = 1/16th. But I now understand it won't work as I thought.

**Comment by Qirky** [comment]
Ah well. What about a menu option that let's you select low/medium/high cpu usage?

**Comment by joesh1** [comment]
Now that could be very useful! I'm using your advice on changing Clock.sleep_time, but a menu option would be perfect, good idea.
