### ISSUE TITLE
starting up on a headless server

### ISSUE THREAD

**Issue by ekg** [Qirky/FoxDot#105]
I'd like to run foxdot on a remote server and stream audio from supercollider using icecast.

Is there a command line only way to install foxdot (including building the quark in supercollider) and also to start foxdot and supercollider?

**Comment by ekg** [comment]
This clarifies how to start foxdot: https://gist.github.com/lvm/c84e4d5ca54f1db256eaa6c98db5b141

**Comment by Qirky** [comment]
If you want to run FoxDot via the command line you can use the `--pipe` flag i.e. `python -m FoxDot --pipe` and press enter twice to run a block of code. As for running supercollider, if you're on Linux or Mac you can just run `sclang` and type `FoxDot.start` from the prompt. You could also create a file that contains the text "FoxDot.start" e.g. `startup.scd` and run `sclang startup.scd` and that will start supercollider and the FoxDot quark.

**Comment by ekg** [comment]
This is not fully resolved. We also need a way to install the foxdot quark and rebuild the supercollider class library from the command line. I found a snippet to do this but have since lost it. I may need to go back to IRC to also for help because it is not documented well.

This would also really help in generating reproducible installations of foxdot. Right now the manual step in scide can cause serious problems if done wrong.

**Comment by ekg** [comment]
@Qirky I've found the command to recompile the class library:

```
thisProcess.platform.recompile
```

(From scattered documentation https://github.com/supercollider/supercollider/blob/f65a1ef7bfb100f4ccb7dcab3a6dff6826be4344/HelpSource/Classes/Main.schelp, and https://github.com/supercollider/supercollider/blob/f65a1ef7bfb100f4ccb7dcab3a6dff6826be4344/HelpSource/Classes/Platform.schelp)

I think this is a FoxDot-level issue, as most users are unlikely to be doing anything with supercollider other than running FoxDot. The installation instructions should include a script that runs the FoxDot quark install and recompiles the class library using this command via sclang rather than the IDE. Ideally, a full install script would warn you if you have existing versions (which may be out of date) installed.

**Comment by Qirky** [comment]
The reason for using SuperCollider as the audio engine is because of the IDE that allows you to go in and do more interesting things, such as edit SynthDefs, and this is quite common practice in live coding (see the [TidalCycles](https://tidalcycles.org/getting_started.html#running) start-up. It gives users much more flexibility when using external systems  such as FoxDot or Tidal, e.g. pressing Ctrl+. to free all nodes when the CPU is overloaded or restart the server (and also displays CPU usage). 

> I think this is a FoxDot-level issue, as most users are unlikely to be doing anything with supercollider other than running FoxDot.

I don't know what you mean by this. There are *many* more people using SuperCollider as opposed to FoxDot. If you mean that most FoxDot users aren't using SuperCollider, then that may be true but its not too much trouble to run `FoxDot.start` in the SuperCollider window.

**Comment by ekg** [comment]
Using the IDE for installation adds a number of human interactions into what should be a basically push-button or copy-paste installation of foxdot. This introduces a number of ways things can fail, and makes it harder to reinstall foxdot to debug what's going on when the installation breaks, which has happened to me enough times that I'm tired of manually driving the installation in supercollider.

Of course more people use supercollider than foxdot. I mean that most foxdot users (at least the handful I know and everyone who I've introduced foxdot to) had zero reason to maintain a supercollider installation before they encountered foxdot.

**Comment by Qirky** [comment]
Ok, will have a think and talk to the SuperCollider community about this

**Comment by DavidS48** [comment]
FWIW, Overtone is able to boot and connect to the server entirely from within the Clojure code, so it seems to be possible! OTOH, I've spent all morning banging my head against it and I couldn't figure out _how_ it does it without using the IDE to register an OSCFunc...

As someone with slightly flaky audio, this is something that I'd be keen to see as it could help to make recovering from crashes easier....

**Comment by Qirky** [comment]
FoxDot originally booted SuperCollider and ran the `FoxDot.start` code but users wanted to be able to check the CPU usage and error log and there was also a few issues with paths but that was over a year ago tbf. I think that Sonic-Pi is packaged with SuperCollider but I wouldn't know where to start to include it in FoxDot

**Comment by DavidS48** [comment]
Ah, okay. It's no big deal if people generally prefer it that way.

**Comment by ekg** [comment]
It's possible to do the setup in sclang from the command line, so many of my concerns were easily resolvable.

I have also established a pattern for running on a server without a sound card. This can be used to generate audio samples or streaming audio on a cloud server. Here's an example: https://github.com/ekg/foxsamply
