### ISSUE TITLE
~ doesn't work on Mac

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#108]
Hi Ryan, maybe you could have a quick look on a mac which for `~` uses `alt+n`. This makes Python quit .... is it some sort of shortcut for 'quit' maybe? Anyhow, it makes using a ride symbol impossible from the samples folder. I've also noticed that the '|' doesn't work either - I can't remember what sound is there.

**Comment by Qirky** [comment]
There's no binding of `alt+n` in FoxDot so it must be part of the Tkinter library or MacOS. Can you open FoxDot and run this line of code:

`FoxDot.text.bind("<Alt-n>", lambda *e: "break")`

or 

FoxDot.text.bind("<Option-n>", lambda *e: "break")

I think the latter one is correct but not sure. Then try inserting the "~" symbol again and let me know what happens.

**Comment by Qirky** [comment]
Also, "|" is no longer mapped to a sound as it is used to specify sample numbers for individuals characters. I'll add the info to the readme as I think it's currently only in the changelog at the moment

**Comment by Qirky** [comment]
The first raises no error but it still crashes?

**Comment by joesh1** [comment]
Indeed.

**Comment by Qirky** [comment]
I can test things on a Mac next week and try and see if I can fix the issue

**Comment by Qirky** [comment]
If you have IDLE installed (the editor that comes with most Python installations) could you try pressing Option+N? I think it might be an inherent bug in TKinter and you'll get the same problem. It seems it's a problem with OS X not shipping the latest version of TK. However if you build Python from source it's possible to get the latest versions:

https://bugs.python.org/issue22566

Could potentially put a shortcut key for tilde, what would you like it to be?

**Comment by joesh1** [comment]
Hi Ryan, I'll have a look at that in the IDLE later, but as for the shortcut I guess a good choice could be `cmd+t`, what do you think?

**Comment by Qirky** [comment]
Added `Cmd+T` / `Ctrl+T` for inserting tilde
