### ISSUE TITLE
print(AllHelp) - part 2

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#109]
#107 - I'm referencing this, which is closed and I think doesn't show up as an issue any more?

Hi, I just checked and saw only `print(SynthDefs)` and `print(Samples)`. What I meant - if you didn't understand - was that if you type `print(AllHelp)` the post window simply prints a list of all the help print statements. Now, it is indeed true, and maybe simpler, to just add the list to the help window `cmd+K`, which I think is your idea. However, what (to me) seems the most important, is that all the main possible topics are posted: `print(Clock.sleep_time)`, `print(SynthDefs)`, `print(Player.get_attributes())`, `print(Scale.names())`,  `help(Patterns)` - I think that's about all?

Most of this stuff you just remember, but it's useful for beginners, and also when you're stuck and looking for something, without having to go to the tutorials just to look for an expression/command etc. 

In the meanwhile, thanks, great work.

**Comment by Qirky** [comment]
Are you running from the repository or from the version on PyPi? The last commit pushed now includes a lot of these commands in the help message, which is accessible by pressing ctrl+h on windows and ctrl+k on Mac. You can also view it by going to Help & Settings -> Display help message. I'll add a couple more print commands for Scales and type of patterns too.
