### ISSUE TITLE
problems making sound on linux

### ISSUE THREAD

**Issue by claudeha** [Qirky/FoxDot#11]
The simplest example 'd1 >> play("x-o-")' fails with an exception in the terminal I started main.py from, as if nothing is listening for OSC on the relevant port.  Here's the complete log, in case something useful is there earlier:

    claude@latte:~/emf/FoxDot$ python main.py 
    /home/claude/emf/FoxDot/FoxDot/SCLang/OSCFunc.scd
    init_OSC
    empty
    compiling class library...
    initPassOne started
            NumPrimitives = 711
    initPassOne done
            compiling dir: '/home/claude/opt/share/SuperCollider/SCClassLibrary'
            compiling dir: '/home/claude/opt/share/SuperCollider/Extensions'
            compiling dir: '/home/claude/.local/share/SuperCollider/downloaded-quarks/Vowel'
            compiling dir: '/home/claude/.local/share/SuperCollider/downloaded-quarks/Dirt-Samples'
            compiling dir: '/home/claude/.local/share/SuperCollider/downloaded-quarks/SuperDirt'
            pass 1 done
    ERROR: Class extension for nonexistent class 'Document'
         In file:'/deprecated/3.7/deprecated-3.7.sc'
            numentries = 821770 / 11419716 = 0.072
            5089 method selectors, 2244 classes
            method table size 12415192 bytes, big table size 91357728
            Number of Symbols 11827
            Byte Code Size 361047
            compiled 318 files in 1.15 seconds
    
    Info: 3 methods are currently overwritten by extensions. To see which, execute:
    MethodOverride.printAll
    
    compile done
    Class tree inited in 0.06 seconds
    Cleaning up temp synthdefs...
    WARNING: Extension in '/home/claude/opt/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIClient:externalSources in main class library.
    WARNING: Extension in '/home/claude/opt/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIClient:externalDestinations in main class library.
    WARNING: Extension in '/home/claude/opt/share/SuperCollider/SCClassLibrary/Platform/linux/extMIDIOut.sc' overwrites Meta_MIDIIn:connectAll in main class library.
    Intentional overwrites must be put in a 'SystemOverwrites' subfolder.
    
    
    *** Welcome to SuperCollider 3.7.2. *** For help type ctrl-c ctrl-h (Emacs) or :SChelp (vim) or ctrl-U (sced/gedit).
    booting 57110
    JackDriver: client name is 'SuperCollider'
    SC_AudioDriver: sample rate = 48000.000000, driver's block size = 2048
    JackDriver: connected  system:capture_1 to SuperCollider:in_1
    JackDriver: connected  system:capture_2 to SuperCollider:in_2
    JackDriver: connected  SuperCollider:out_1 to system:playback_1
    JackDriver: connected  SuperCollider:out_2 to system:playback_2
    SuperCollider 3 server ready.
    JackDriver: max output latency 128.0 ms
    Receiving notification messages from server localhost
    Shared memory server interface initialized
    File '/home/claude/emf/FoxDot/FoxDot/Samples/foxdot/cs1.wav' could not be opened: System error : No such file or directory.
    File '/home/claude/emf/FoxDot/FoxDot/Samples/foxdot/bd2.wav' could not be opened: System error : No such file or directory.
    File '/home/claude/emf/FoxDot/FoxDot/Samples/foxdot/bd1.wav' could not be opened: System error : No such file or directory.
    File '/home/claude/emf/FoxDot/FoxDot/Samples/foxdot/cs1.wav' could not be opened: System error : No such file or directory.
    File '/home/claude/emf/FoxDot/FoxDot/Samples/foxdot/bd2.wav' could not be opened: System error : No such file or directory.
    File '/home/claude/emf/FoxDot/FoxDot/Samples/foxdot/bd1.wav' could not be opened: System error : No such file or directory.
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    File '/home/claude/emf/FoxDot/FoxDot/Samples/foxdot/tom3.wav' could not be opened: System error : No such file or directory.
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:sine
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    WARNING: keyword arg 'releaseTime' not found in call to Meta_Env:new
    WARNING: keyword arg 'level' not found in call to Meta_Env:new
    Exception in thread Thread-1:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 763, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/home/claude/emf/FoxDot/FoxDot/TempoClock.py", line 104, in run
        item()
      File "/home/claude/emf/FoxDot/FoxDot/Players.py", line 201, in __call__
        self.send()
      File "/home/claude/emf/FoxDot/FoxDot/Players.py", line 590, in send
        self.server.sendNote( self.SynthDef, osc_msg )
      File "/home/claude/emf/FoxDot/FoxDot/ServerManager.py", line 59, in sendNote
        self.sendOSC(packet)
      File "/home/claude/emf/FoxDot/FoxDot/ServerManager.py", line 54, in sendOSC
        self.client.send( message )
      File "/home/claude/emf/FoxDot/FoxDot/OSC.py", line 1222, in send
        raise OSCClientError("while sending: %s" % str(e))
    OSCClientError: while sending: [Errno 111] Connection refused

**Comment by claudeha** [comment]
It seems to be a threading issue, maybe a race condition, as when I quit foxdot it prints "result=0 \n booting server".

**Comment by Qirky** [comment]
Hmm, that's a strange one. Does it do this every time, and do you have SuperCollider running when starting FoxDot? 

Could you run FoxDot again and check the ports that sclang / scynth are listening on? Thanks

**Comment by claudeha** [comment]
It does it every time I start FoxDot (which does start SuperCollider itself).  It only happens on the first attempt to run code from FoxDot, I guess the thread dies at that point so no more exceptions are printed.  Here is some netstat output:

    Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
    udp        0      0 localhost:48118         localhost:57110         ESTABLISHED 1679/python     
    udp        0      0 localhost:46130         localhost:57120         ESTABLISHED 1679/python     
    udp    76544      0 localhost:33946         localhost:57110         ESTABLISHED 1679/python     
    udp        0      0 *:57110                 *:*                                 1688/scsynth    
    udp        0      0 *:57120                 *:*                                 1680/sclang     
    udp        0      0 localhost:46948         localhost:57120         ESTABLISHED 1679/python     

That high recv-q value looks suspicious, but I don't know much about networking.. it occurs even before trying to execute code in FoxDot, straight after startup.  I'm guessing the recv-q is filled with replies to python from SC after FoxDot adds its stuff on boot?  Maybe it needs to be explicitly read to avoid clogged tubes..

**Comment by claudeha** [comment]
I think I figured it out - in `Server.__init__()` the OSC clients attempt to connect to SC but it isn't running yet.  I rejigged it a bit to `self.boot()` in the `__init__()` method, now I can get sound, though it seems to start sclang again on exit after sending /quit for some reason I don't understand.  So I `killall sclang` after I'm done after `python main.py` finishes.  Maybe you have a better fix, my patch attached...
[0001-boot-server-before-trying-to-connect-to-it.patch.txt](https://github.com/Qirky/FoxDot/files/416727/0001-boot-server-before-trying-to-connect-to-it.patch.txt)

**Comment by Qirky** [comment]
The `BufferManager`  class was creating a new instance of `ServerManager` instead of using the same one, which meant that putting the `Server.boot()` method in the constructor booted the server twice. I've moved things around so that the server boots, waits 5 seconds, then connects the OSC client. I'd like to be able to see if SuperCollider is running on the port first (in case there is already an instance running or something) but because it's UDP I'm having some trouble doing that. Hopefully this boots ok for you but you may need to adjust the 5 second wait time.

**Comment by claudeha** [comment]
Works great now, thanks!
