### ISSUE TITLE
timing issues + sync problems

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#111]
Hi Ryan, I'm getting a lot of problems with sync/timing as I build up code. It's the typical issue that one gets on SuperCollider when your post window starts saying "`late 0.127071685`" etc. Have you got any suggestions? I've tried making sure the various clocks are not too short by using 'high CPU' usage, but nothing seems to help. Any suggestions welcomed!

Thanks in advance - Joe

**Comment by CadaverLab** [comment]
I've had this issue as well. @Qirky suggested i use
```
Clock.latency=0.4
Clock.sleep_time=0.01

```
 Which seems to have worked, but i haven't been doing much playing with FoxDot lately so i should try it again

**Comment by Qirky** [comment]
Yes, I think adjusting `Clock.latency` is probably the best thing here. It gives FoxDot a bit more time to prepare the messages being sent to SuperCollider. If you are getting late messages it means that the message is arriving after the timestamp at which it was meant to activate. I'll add a similar menu option for latency  as CPU usage

**Comment by joesh1** [comment]
Nice, thanks.

**Comment by Qirky** [comment]
Recent changes have helped with timing issues, so closing this now
