### ISSUE TITLE
Record from within FoxDot

### ISSUE THREAD

**Issue by dirkbosman** [Qirky/FoxDot#124]
I don't know if you have a feature-roadmap / trello-board, but thought I post it here. 

Is there anyway to integrate the SuperCollider Recording Commands within FoxDot?
- Server.default.record
- Server.default.stopRecording

**Comment by Qirky** [comment]
Hiya, I'm trying to use the GitHub projects tab but update it pretty infrequently: https://github.com/Qirky/FoxDot/projects/1

This is a nice idea and would be a good addition - thanks!

**Comment by dirkbosman** [comment]
Awesome! No probs!
