### ISSUE TITLE
assigned Player alias won't get stop() method

### ISSUE THREAD

**Issue by Naruto0** [Qirky/FoxDot#134]
## Steps to reproduce

- create player object with user defined name `foo = Player()`
- feed player with instrument `foo >> pluck()`
- Stop user defined player `foo.stop()`

## Actual behavior

User defined player keeps on playing. Have to use `Clocks.stop()` to stop user defined class alias.

I am using FoxDot v0.7.6.

https://github.com/Qirky/FoxDot/blob/49753b2cd9111283222dc44cf6146761815cba77/FoxDot/demo/01_playing_notes.py#L17

It seems that the method is only working with default player aiases.

**Comment by Qirky** [comment]
What OS and version of Python are you using? I can't reproduce this behaviour on my machine

**Comment by Naruto0** [comment]
Hi Ryan,

I'm using Python 3.6.1 on Windows 8. 

I wonder if there's any `--debug` option for FoxDot? I will try to reproduce and reach back with more info.

**Comment by Qirky** [comment]
Is there any chance you run the code twice?
```python
foo = Player()
foo >> pluck()
```

If you run it again,  you'll create a new `Player` called `foo` and lose the reference to the old one so `foo.stop()` only stops the last one created.

**Comment by Naruto0** [comment]
Hi @Qirky, that's exctly as you said. So than that's rahter python behaviour, not FoxDot specific.

You may close the issue.
