### ISSUE TITLE
MemoryError in stutter on low spec laptop

### ISSUE THREAD

**Issue by christopheredsall** [Qirky/FoxDot#136]
At PyCon UK 2018 I was going through Ryan's workshop using  https://github.com/Qirky/FoxDot-Worksheet. SuperCollider is 3.8 and FoxDot 0.7.8.

When I got to line 276

```
d1 >> play("x-o-").every(4, "stutter", 4, dur=3)
```

The console shows

```
>>> d1 >> play("x-o-").every(4, "stutter", 4, dur=3)
MemoryError in 'stutter': 
MemoryError in 'stutter': 
```

The laptop doesn't have a huge amount of RAM

```bash
chris@blue:~/pyconuk18/sc$ free -m
              total        used        free      shared  buff/cache   available
Mem:           1853        1102         250         197         500         405
Swap:          1358         616         742
```

As a whole python isn't using a large percentage of the memory

```
chris@blue:~/pyconuk18/sc$ top

top - 13:08:08 up  2:45,  1 user,  load average: 1.49, 1.51, 1.51
Tasks: 229 total,   1 running, 192 sleeping,   0 stopped,   0 zombie
%Cpu(s): 29.1 us,  6.7 sy,  0.0 ni, 63.7 id,  0.0 wa,  0.0 hi,  0.5 si,  0.0 st
KiB Mem :  1897556 total,   125172 free,  1187336 used,   585048 buff/cache
KiB Swap:  1391612 total,   760812 free,   630800 used.   370308 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                   
13348 chris     20   0  406656  47392  17860 S  54.3  2.5   5:04.30 python    
```

**Comment by Qirky** [comment]
Managed to trace the error to the fact that `___getslice___` in Python 2 doesn't use `None` by default as the end value but actually some huge integer. Coupled with the behaviour of FoxDot patterns when indexed to grow to the end size if it is larger than the pattern, it was creating huge arrays of data in Python 2. That has now been fixed (and I'm no longer using  `__getslice__` as I've discovered it was deprecated in Python 2.6) and I will update the PyPI version soon!
