### ISSUE TITLE
Ctrl + = doesn't change font size

### ISSUE THREAD

**Issue by kfrncs** [Qirky/FoxDot#137]
Keyboard shortcuts for fontsize only move the window split around.. Doesn't change the font size. Running Manjaro GNOME. Let me know if there's any more info I can give.

**Comment by Qirky** [comment]
If you go to the "Edit" menu and click "Increase Font Size" does that do the same thing too?

**Comment by kfrncs** [comment]
it does nothing

**Comment by kfrncs** [comment]
>>> print(FoxDot.font.actual())
{'family': 'fixed', 'size': 10, 'weight': 'normal', 'slant': 'roman',
'underline': 0, 'overstrike': 0}

**Comment by Qirky** [comment]
I think it is to do with the "fixed" font family I guess. Can you try the following code:

`FoxDot.font.config(family="mono")`

You can change the `family` value to another font if you like, then try changing the font size again?

**Comment by kfrncs** [comment]
It's giving the same behaviour after changing the font family

**Comment by Qirky** [comment]
Does the font change after running the code above? Could you try the following:

`FoxDot.font.config(family="mono", size=16)`

It's probably best to do this with the window maximised. If you could play around with the font family / size and let me know how you get on that'd be great.

**Comment by kfrncs** [comment]
Figured it out! The font family was defaulting to "fixed" because I didn't
have any of the fonts that were in the if clause.. Once I assigned console
& editor to a font family that was installed on my computer, I can change
the font size. I don't know how to make it check if a font is installed, so
I just hardcoded mine to change the font.

Thanks for your help. :)

**Comment by kfrncs** [comment]
There's a method in tkfont (.families())
http://infohost.nmt.edu/tcc/help/pubs/tkinter/web/fonts.html

It lists the font families. Maybe could be used to say "if x font is available... else: take the first one". I'm on a train in Europe right now so I don't have time to sit down and fix the problem for future cases, but it's fixed for me.

**Comment by Qirky** [comment]
Ah ok, thanks! I think  the issue with the "take the first font" will be if the first font is not very nice. For example the  first font is "terminal" on my machine and is a pixelated monospace font. I will look at trying to use the "TkFixedFont" as a default and make sure it changes size.

**Comment by Jennyytt** [comment]
I have a similar problem here with Fedora, running KDE. Ctrl + = moves the vertical line between the line numbering box and code editing box to the right while ctrl + - does nothing. The error below is returned after trying with ```FoxDot.font.config(family="mono")```

```
File "/home/jenny/miniconda3/envs/foxdot/lib/python3.9/site-packages/FoxDot/lib/Code/main_lib.py", line 155, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 1, in <module>
    from __future__ import absolute_import, division, print_function
AttributeError: '_util' object has no attribute 'font
```
