### ISSUE TITLE
Error on startup: icon not defined

### ISSUE THREAD

**Issue by theseanco** [Qirky/FoxDot#14]
'tkinter.TclError: bitmap "/home/smc/src/github/FoxDot-master/FoxDot/Workspace/foxdot.ico" not defined'

OS: Kubuntu 16.04

![foxdoterror](https://cloud.githubusercontent.com/assets/8597971/20271716/965abc8c-aa83-11e6-93f5-e3e69e8c8d9f.png)

**Comment by theseanco** [comment]
Fixed by commenting out self.root.iconbitmap(FOXDOT_ICON) in FoxDot/Workspace/Editor.py, but this doesn't address the root issue!

**Comment by Qirky** [comment]
Seems like it was a Linux issue using .ico files and now uses a .gif. If you could try it now on a Linux OS and let me know that'd be great. Thanks.

**Comment by theseanco** [comment]
Yup, sorted!
