### ISSUE TITLE
Pwalk start does not seem to work.

### ISSUE THREAD

**Issue by WiggyWire** [Qirky/FoxDot#142]
print(PWalk(start=6)[:16])
>>> # Start at a non-zero number
... print(PWalk(start=6)[:16])
P[0, -1, -2, -3, -4, -3, -4, -5, -6, -5, -4, -5, -6, -7, -6, -7]

>>> # Start at a non-zero number
... print(PWalk(start=5)[:16])
P[0, 1, 0, 1, 2, 1, 0, 1, 2, 1, 0, 1, 0, -1, -2, -1]

>>> # Start at a non-zero number
... print(PWalk(start=4)[:16])
P[0, -1, -2, -3, -4, -5, -4, -5, -6, -7, -6, -7, -6, -7, -6, -5]

**Comment by Qirky** [comment]
Ah thanks for the catch - I've set the default start to be the value specified and not 0
