### ISSUE TITLE
message formatting for self.forward

### ISSUE THREAD

**Issue by micuat** [Qirky/FoxDot#151]
I'm new to this so I'm not sure if I'm right, but isn't

https://github.com/Qirky/FoxDot/blob/master/FoxDot/lib/ServerManager.py#L281

should be

```
            self.forward.send(osc_message)
```

and

https://github.com/Qirky/FoxDot/blob/master/FoxDot/lib/ServerManager.py#L594

should be

```
            self.forward.send(msg)
```

?

**Comment by Qirky** [comment]
Yup you're right! I've updated the code. Feel free to make a pull request if you find any other code that needs changing in future :)
