### ISSUE TITLE
swell effect

### ISSUE THREAD

**Issue by satelliteray** [Qirky/FoxDot#153]
This may be my poor usage, but I can't get the swell effect to work. Whichever value I use doesn't seem to affect the sound. From the FxList I see that it relies on sus, but again changing sus and having swell doesn't seem to do anything.

**Comment by Qirky** [comment]
Hiya, swell should be a frequency value, e.g. 2000 that the hpf goes up to then returns to 0 but because most effects have values around 0-1 I've changed the swell to be multiplied by 2000 i.e. `swell=1` sets the swell frequency 2000.

**Comment by satelliteray** [comment]
Sweet!
