### ISSUE TITLE
FoxDot forums

### ISSUE THREAD

**Issue by qantuum** [Qirky/FoxDot#156]
Hello there,

not related with this app's GitHub content but still a bit hacky...

I need to register in the discussions forum on the FoxDot official website and, no matter what I do in my registration process, this captcha generator never lets me in. I receive error msg "bot suspected". EG : when I answer "seventeen minus 16" with "1" or with "one", or "One", the door should open, but it does not.

To  handle that matter, I would suggest the "true" flag for filtering the questions' answers, has a malfunction of some sort.

I think I'd address this one because I can see the FoxDot community is still somewhat underground, and I would appreciate to become part of it and try to make it thrive.
At the moment I am preparing a FoxDot basics manual, all in French, for scholar purposes. So at least it will get a bit of exposure within my peers.

Thanks.

**Comment by satelliteray** [comment]
Same - no matter what I enter I get a "suspected bot" message and another verification question

**Comment by Qirky** [comment]
Very common at the moment so making this a high priority issue

**Comment by Qirky** [comment]
Managed to register a new account after having the same issues mentioned above. Can you try registering again and let me know if you get any success?
