### ISSUE TITLE
Use of slideto and slidefrom

### ISSUE THREAD

**Issue by satelliteray** [Qirky/FoxDot#159]
I'm having trouble using the slideto and slidefrom features to slide from one note to another. I want the choose the midi note on both ends of the slide. The best I've come up with is using a function to use midi notes like so in  a chromatic scale:

```python
Clock.clear()
def midislide(note):
    return math.pow(1.059,note)-1
Scale.default = "chromatic"
b1 >> dbass(0, dur=1, slidefrom=[midislide(3),0,0,0],slidedelay=.5)
```

Is  this the way to go or am I missing something?

**Comment by Qirky** [comment]
I have been thinking about this, this might be the only way to achieve what you're after *but* I am planning on adding something along the lines of:

`p1 >> pluck([0, 4, 7, 11], glide=[0, 0, 4, 0])`

This would be similar to using slide but would change the pitch by 4 steps in the scale. Not sure if it's best to use scale steps or semitones though, so feedback is welcome

**Comment by satelliteray** [comment]
That would be perfect. Scale steps would be more in keeping with the FoxDot approach. I personally prefer semitones for my use, but it's great that FoxDot manages everything with scales, so anyone with a go-to scale can fit it in with their habits and flow with their regular signature patterns.
