### ISSUE TITLE
bar arguments

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#160]
Hi Ryan

This isn't an issue, just a suggestion, but when using the `var([1,0] 8)` argument in amplitude the other day it suddenly dawned on me the a 'bar' argument could be very useful. At present if one wants to silence a line (or synth) for 'x' time, they have to think in terms of beats. To make this one at present has to type 4*4, or whatever. However, it could be great to be able to type an alternative:

`amp = var([0,1], bar = 4)`
or
`amp = var([0,1], bar(4))`

or something similar, which would also make for easy reading. This could be very useful in various situations, not only `amp`. 

Excuse me if this already exists in FoxDot, I just haven't (as yet) come across it in the documentation.

**Comment by Qirky** [comment]
You can use `Clock.bars(4)` but that is quite a bit of typing. Could be nice have a variable called `bar` that returns 4 (or whatever the value should be) but could be "called" that returns the multiple e.g. `bar(4)` is 4x4.

**Comment by Qirky** [comment]
Going to close the issue. Realised you can run `bar = Clock.bars` to have access to a short-hand version of the command.
