### ISSUE TITLE
no module named FoxDot

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#167]
Hi Ryan, we're trying to run (and install) FoxDot on a school computer (Windows 10), but we can't get it to run. SC is installed, the quark to, and FoxDot downloaded from Git. However, when we run the `python -m FoxDot` command we just get `no module named FoxDot`. Where are we going wrong - any suggestions more than welcome!

Thanks in advance.

**Comment by Qirky** [comment]
You'll need to make sure you're in the correct directory when running the command. You'll need to use `cd` to the path to the FoxDot folder (the one with `setup.py` in) and run `python -m FoxDot`. If you want to run it from anywhere, you'll have to install it by running `python setup.py install` in the same directory. Hope that helps!

**Comment by joesh1** [comment]
Thanks Ryan, we'll try that later and let you know if we still have any problems.

**Comment by Qirky** [comment]
Hi, has this issue been solved?

**Comment by Qirky** [comment]
Can you let me know if I can close this issue?

**Comment by Kebbz** [comment]
Hi, I've came across the same issue and the solution works as charm. Thank you!

**Comment by joesh1** [comment]
Sorry Ryan, I didn't see this. We changed computers at school, so the issue was never resolved, although it works on my mac, so I guess it works fine on a PC.
