### ISSUE TITLE
Bpm with linvar problem

### ISSUE THREAD

**Issue by CrashServer** [Qirky/FoxDot#175]
Got a lot of "late" in SC when I do for example : 
`Clock.bpm = linvar([48,128],[16,inf], start=now)` 
and after (16 bars) try to change it to `Clock.bpm = 48`

**Comment by Qirky** [comment]
Ah there seems to be an issue when going between "flexible" time and "hard" time i.e. a linvar and a single number. I've updated FoxDot to better handle changing between these and also not to send messages that are going to be late. Thanks for the catch - I'll update the pip version later today
