### ISSUE TITLE
Problem on start with WSL

### ISSUE THREAD

**Issue by zeitkunst** [Qirky/FoxDot#179]
I'm trying to make FoxDot work in a Windows Subsystem for Linux (WSL) bash shell running in ConEmu, but I'm having problems. I can get things to work properly using a Windows installed python, but if I try and use the python installed in Ubuntu in WSL (or the conda version installed there), I get the dreaded message `Warning: Could not fetch info from SCLang server. Using defaults...` and the errors:

```
*** ERROR: SynthDef startSound not found
FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef pluck not found
FAILURE IN SERVER /s_new SynthDef not found
*** ERROR: SynthDef makeSound not found
FAILURE IN SERVER /s_new SynthDef not found
```
Even if I try using code that you've suggested elsewhere...

```
(
OSCFunc(
{
arg msg, time, addr, port;
var fn;

// Get local filename

fn = msg[1].asString;

// Print a message to the user

("Loading SynthDef from" + fn).postln;

// Add SynthDef to file

fn = File(fn, "r");
fn.readAllString.interpret;
fn.close;

},
'foxdot'
);
)
```

...I can't get things to work properly. (I have called FoxDot.start in supercollider before starting the editor with `python -m FoxDot`). So I assume there's something about the interface between WSL and Windows that isn't working. I could always try and install supercollider within WSL, but I doubt jack and WSL will behave properly. Do you have any suggestions of how I could go about debugging this issue? Thanks!

**Comment by zeitkunst** [comment]
Looks like jack and WSL _don't_ interface nicely, so running sc in WSL is out of the question, unfortunately.

**Comment by zeitkunst** [comment]
Ahh, I figured it out...Windows SuperCollider is trying to read FoxDot's scd files using their location in the WSL filesystem, which of course Windows SC won't be able to read. Seems like the only way to handle this would be a) a check for whether or not one is running in WSL; b) if so, a directive to load the scd files from a path that is available to Windows, which might require one to install FoxDot using Windows python anyway. As this is likely to be a really rare use case--i.e., I wanted to run FoxDot from WSL so that I don't have to have multiple versions of Python on my system--feel free to close this ticket.

**Comment by Qirky** [comment]
Sorry I wasn't able to help but it seems like you managed to get to the bottom of it anyway.
