### ISSUE TITLE
Timing issues

### ISSUE THREAD

**Issue by sebastianneubauer** [Qirky/FoxDot#18]
Hi,
just started to play around with foxdot and it is really awsome!

One issue I found, it seems that the timing is not always exact. 
In a simple
`d2 >> play("-")`
the tick sometimes lags noticable behind.

Is this a known issue or is it just in my setup (windows 10)? 

With some hints on how the timing works in foxdot I can also try to improve this if it turns out this is a real issue...

**Comment by Qirky** [comment]
Hi sebastian,

Are you running any other high CPU applications at the same time? FoxDot has a dedicated thread that sleeps for a maximum of one beat or until the next scheduled event. If there are several scheduled events scheduled simultaneously then FoxDot loops over these and sends them one after another to SuperCollider but the time delay between them should be negligible - is that what is happening, or is it inconsistent beat durations for some events?
