### ISSUE TITLE
Wrong key bindings in Mac OS Mojave

### ISSUE THREAD

**Issue by benmaier** [Qirky/FoxDot#180]
I recently installed FoxDot v0.7.28 on Python 3.7 for Mac OSX Mojave. The only keybinding that seemed to work was "Cmd+Return" which only ran the current line instead of the block as expected. Upon inspection of the code it seems that TKinter confuses "Option" with "Command". I replaced the following lines 

https://github.com/Qirky/FoxDot/blob/master/FoxDot/lib/Workspace/Editor.py#L202

with 

```python
         ctrl = "Mod2" if SYSTEM == MAC_OS else "Control"
         alt = "Control" if SYSTEM == MAC_OS else "Alt"
```

Now I can use all "Cmd+<Key>"-bindings as expected and for running single lines I use "Ctrl+Return". Seems fair enough to me.

I can open a pull request if you want.

**Comment by Qirky** [comment]
That's a good catch - I'm not able to test on any Mac OS so having users find these bugs is super helpful. Do feel free to make a PR.
