### ISSUE TITLE
Dead Players bug

### ISSUE THREAD

**Issue by CrashServer** [Qirky/FoxDot#184]
Sometimes when you make a mistake or you try unauthorized things, you get an error and the player is dead. This mean, it stops making sound and you can't resume it or restart it. 
Sometimes a `Clock.clear()` is enough but sometimes you have to restart Foxdot because even a `Master.reset()` is not enough.

It is more generally a problem on error exceptions and here is an example among others:
`a1 >> blip ("x")`

**Comment by Qirky** [comment]
I've updated it to print errors instead of raising them. This will stop Players being un-scheduled but still tracked in the clock and should fix the issue.
