### ISSUE TITLE
Versions on github and pypi are not the same

### ISSUE THREAD

**Issue by dvzrv** [Qirky/FoxDot#187]
Hi!
I would like to package foxdot for Arch Linux. However, I realized, that the versions here and on pypi are not the same.
On pypi we're at [0.7.33](https://pypi.org/project/FoxDot/#history) and here at [0.7.16](https://github.com/Qirky/FoxDot/tags).

I would like to point out, that diverging versioning is not good, as this leads to major confusion for packagers (and also users), in case  they would like to report a bug. Additionally, this breaks transparency and reproducibility. Anyone could have hacked the pypi account and publish malicious code right now. There's no way of tracing this to a released version here on github. 

Please tag the appropriate commits!

A good, standard workflow is usually: tag commit -> create sdist/wheel -> publish to pypi.

Thanks!

**Comment by dvzrv** [comment]
Hey @Qirky, could you please tag the version 0.7.38? I'm unfortunately unable to build 0.7.36.

**Comment by Qirky** [comment]
From pip? You need to update your setuptools and wheel probably first. Will tag the release though.

**Comment by dvzrv** [comment]
Hey @Qirky, could you please tag the version 0.7.41? Until #188 is fixed, I'm building from  the github tarball.

Also, having the same versions available here and on PyPi offers proper transparency to people using FoxDot, which code they are actually using, as noone can otherwise be sure, which version on PyPi is which commit in this repository.

**Comment by ftoledo** [comment]
I'm working on debian package and have same issue, when FoxDot startup that say that have new version on pip, but github release still on 0.8.1
