### ISSUE TITLE
Computer crashing upon launch

### ISSUE THREAD

**Issue by sachiniyer** [Qirky/FoxDot#191]
I am running a 2015 MBP with about 4 gb of free memory. I was able to install FoxDot, and Supercollider functions well. When I run FoxDot, it redirects to Supercollider and then crashes. Is this because my computer does not have enough memory, or is it indicative of a larger problem?

<img width="540" alt="Avaliable_Memory" src="https://user-images.githubusercontent.com/38194905/62757581-94d9a980-ba30-11e9-9072-0245c51be346.png">
[FoxDot_problem.mov.zip](https://github.com/Qirky/FoxDot/files/3484953/FoxDot_problem.mov.zip)

**Comment by Qirky** [comment]
What version of Python / FoxDot / Mac OS are you using? I have never seen that before. FoxDot doesn't require very much memory but can eat up CPU cycles if there is a lot going on. However, this is on boot up, which is very weird. There was error in the last update for Python 2 users but that has been fixed. Try updating by running `pip install FoxDot -U` and try again?

**Comment by sachiniyer** [comment]
I was running python 3.7.4, the latest version of FoxDot, and Mac OS 10.14.6. I finally got it working by deleting all of the python (2.7.4, 3.6, 3.7) of my computer including conda and any other python environments. I reinstalled just python 3.7, and I was able to get it to work by using just python3 and FoxDot.

Also, thank you for the quick response.
