### ISSUE TITLE
Feature request: loop() stretch to fill duration

### ISSUE THREAD

**Issue by jwmatthys** [Qirky/FoxDot#193]
Is it possible to add an option for loop to simply interpolate a full audio loop over a given duration (not preserving pitch)?

Something like:

`loop("my16beatloop.wav", dur=16, beat_stretch=True)`

**Comment by Qirky** [comment]
Added the ability to beat stretch by using `beat_stretch` and setting it to a non-zero value, which can be True.

**Comment by jwmatthys** [comment]
Works great. Thanks!
