### ISSUE TITLE
Connect with multiple servers (Integration with Processing)

### ISSUE THREAD

**Issue by berinhard** [Qirky/FoxDot#194]
Hey, first of all, congratulations for your work in FoxDot! I had the opportunity to recently host an Algorave with @diegodukao and it's only possible because of FoxDot and Troop. Thanks for this time we've had the opportunity to have =]

Besides using FoxDot and Troop, I wrote a [very raw implementation](https://github.com/berinhard/sketches/blob/master/foxdot_001/foxdot_001.pyde) (we were live coding) of a FoxDot's integration with Processing using the Python Mode. To integrate with Processing, I had to introduce a few quick and dirt code changes. I changed the `ServerManager` class to have a new hardcoded client called `processing_client` to connect with Processing's OSC Server. Something like:

```python
self.client = OSCClientWrapper()
self.client.connect( (self.addr, self.port) )
self.processing_client = OSCClientWrapper()
self.processing_client.connect( ('127.0.1.1', 12000) )
```

Then, I duplicated every calls from `self.client` to also be called from `self.process_client`. Here's part of my `sendOSC` implementation:

```python
    def sendOSC(self, osc_message):
        """ Sends an OSC message to the server. Checks for midi messages """
        if osc_message.address == OSC_MIDI_ADDRESS:
            self.sclang.send( osc_message )
        else:
            self.client.send( osc_message )
            self.processing_client.send( osc_message )
```

I took a look at #152 and it seems that there's already a way to configure SuperCollider's connection via `FoxDot/lib/Settings/conf.txt` file. Do you think providing a way to connect to multiple servers is a nice thing to have too? It would be super helpful for me at least :+1: 

Do you have any ideas or suggestion on which direction I could follow? I mean, I'll use this stack in future events, so I'll have to implement it somehow it works for me. But it would be nice to know it from you too :+1:

**Comment by Qirky** [comment]
There is a "forwarding" functionality of the ServerManager that doesn't require hard-coding any changes to the server. Does this do the trick for you?

https://foxdot.org/docs/sending-osc-messages/

**Comment by berinhard** [comment]
Thanks @Qirky! I'm sorry I've missed this in the docs and I'll try it out.
