### ISSUE TITLE
Mac always restarted whenever i started FoxDot and even Troop

### ISSUE THREAD

**Issue by RanggaPAji** [Qirky/FoxDot#204]
So one day i tried to open FoxDot and it seems fine with all the preparation. I typed the `python -m FoxDot` on my terminal and it started as the usual. Then, a window pops-out asking me like do i want to reload the last work that i've been working before. so i clicked yes. But then suddenly my laptop just restarted by it self.
Everything were restarted and then I tried to start it again, but it still does the same thing. I tried to open Troop this morning and it does the same too.
Does anyone have an idea about what should i do?
It doesn't show any error. but this is what i got on the Terminal:

<img width="682" alt="Screen Shot 2019-09-18 at 10 19 07" src="https://user-images.githubusercontent.com/37600867/65105033-cebda880-d9fd-11e9-80c7-47191b71bd41.png">

and this is my Mac info:

<img width="698" alt="Screen Shot 2019-09-18 at 10 20 39" src="https://user-images.githubusercontent.com/37600867/65105086-fca2ed00-d9fd-11e9-929c-e174ee443f60.png">

**Comment by Qirky** [comment]
Are you using a 3rd party distribution of Python e.g. Anaconda? It seems like this is a [known issue](https://stackoverflow.com/questions/57400301/how-to-fix-tkinter-every-code-with-gui-crashes-mac-os-with-respring). Unfortunately it looks like it’s an issue with your version of Python so you either need to install and use Python 2 or re-install Python 3.

**Comment by RanggaPAji** [comment]
Yes, now it's working!. I did uninstall the Anaconda and then re-install Python 3. Worked perfectly. Thanks

**Comment by Qirky** [comment]
Glad it worked - sorry you had to uninstall Anaconda :(
