### ISSUE TITLE
foxdot crash when assign Clock to a number

### ISSUE THREAD

**Issue by CrashServer** [Qirky/FoxDot#205]
I know it's a mistake but Foxdot crash completely (need to kill it) when you try this:
`Clock = 60` instead of `Clock.bpm = 60`

**Comment by Qirky** [comment]
I'll add an alias called `_Clock` so that  you if this does happen you can just re-assign it using `Clock = _Clock`. Plus I'll make sure the back-end calls to clock use `_Clock` so it will work no-matter what you assign to `Clock`.
