### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#207]
Hi Ryan, this isn't a bug report, more of a suggestion. 

I always notice that when using a print(FxList) command, that it could be incredibly useful to have the FXs listed in alphabetical order. As you can imagine - if you don't know all by heart - looking for something can be a little confusing scanning up and down, rather than looking alphabetically.

**Comment by Qirky** [comment]
Updating the FxList (which is now just `Effects` but FxList also works) is on my to do list as it's not very informative. Will close this when I do.

**Comment by joesh1** [comment]
Great, thought it might be useful.

**Comment by Qirky** [comment]
Added in last commit
