### ISSUE TITLE
reading commands from a pipe

### ISSUE THREAD

**Issue by ekg** [Qirky/FoxDot#217]
How could I pipe commands into foxdot? I'd like to use it in extramuros, and this seems to be the way to do it: https://github.com/dktr0/extramuros/issues/11#issuecomment-538577246

**Comment by Qirky** [comment]
Running `python -m FoxDot -h` will show you a list of command line arguments including `-p` and `--pipe`, which allow you to run it from the command line. Note you need an extra newline to "submit" the code to be executed (so you can have multiline code in things like functions)

**Comment by ekg** [comment]
Excellent, thanks for clarifying.
