### ISSUE TITLE
Piano/Klank/Bitcrush classes not defined

### ISSUE THREAD

**Issue by Kebbz** [Qirky/FoxDot#221]
Hi,
I came across a problem with synthdef classes, which are missing „( )“ in their definition files and so, they‘re not recognised by Supercollider. Even though I changed it manually, when I‘m booting FoxDot server they are changed back to wrong syntax.

The story goes like this:
1. I'm changing the file manually by adding "( )",
2. Starting FoxDot in SuperCollider - files remain correct,
3. Staring FoxDot in cmd - files are corrupted again, I'm getting messages in SC that classes are not defined. 

I‘ve installed SC3 plugins but the problem persists. I would be glad for any help in this matter.
Thanks!

**Comment by Qirky** [comment]
Hi, can you supply a bit more information to help identify the problem? Things work fine for me so it could be different versions of SC/Python.

Where are the brackets missing? And for which files? Can you copy and paste the error messages completely? What version Python and SuperCollider are you using?

Thanks

**Comment by Kebbz** [comment]
Hi, Brackets are missing at the beggining and the end of .scd files in FoxDot\osc\scsyndef folder. 
I guess SC needs it to interpret code between them. 

I'm using SuperCollider 3.10.3, and Python 3.7.3

It results with error message: 
"Loading SynthDef from C:\Users\Admin\FoxDot\FoxDot\osc\scsyndef/piano.scd
ERROR: Class not defined.
  in interpreted text
  line 15 char 12:

  osc=MdaPiano.ar((freq[0]), vel: (40 + (amp * 60)), decay: (sus / 4));"
 Thanks for support

**Comment by Qirky** [comment]
Can you copy and paste the contents of the file as it seems they are different to mine regarding brackets.

As for `Class not defined` that means SC3 plugins are not installed correctly as `MdaPiano` is an SC3 plugin synth. You can disable these features from the FoxDot menu in the mean time to see if the synthdefs load correctly in the mean time if you can't install SC3 - [this link might be useful](https://foxdot.org/installation/).

**Comment by Kebbz** [comment]
Here's piano.scd: 

SynthDef.new(\piano,
{|amp=1, sus=1, pan=0, freq=0, vib=0, fmod=0, rate=0, bus=0, blur=1, beat_dur=1, atk=0.01, decay=0.01, rel=0.01, peak=1, level=0.8|
var osc, env;
sus = sus * blur;
freq = In.kr(bus, 1);
freq = [freq, freq+fmod];
amp=(amp * 0.7);
osc=MdaPiano.ar((freq[0]), vel: (40 + (amp * 60)), decay: (sus / 4));
env=EnvGen.ar(Env(times: [sus],levels: [(amp * 1), (amp * 1)],curve: 'step'), doneAction: 0);
osc=(osc * env);
osc = Mix(osc) * 0.5;
osc = Pan2.ar(osc, pan);
	ReplaceOut.ar(bus, osc)}).add;

You're absolutely right, I must have messed something up with plugins. When I turned them off, klank is working again. I've also noticed that without plugins scsynthdef files aren't wrapped with brackets, with plugins they are (at least most of them in my case). Only strange thing is I cannot change them to see if they could be "fixed" because they are overwritten every time I start FoxDot.
