### ISSUE TITLE
Questions. NRT (exporting to .wav)?

### ISSUE THREAD

**Issue by Catsvilles** [Qirky/FoxDot#232]
Hi! I want to get started with SuperCollider but Sclang syntax kinda looks scary, so I'm thinking of getting started with something like Foxdot instead :)
I have a few questions though (cannot find anything about it)

- Is it possible to write a song using Foxdot and then render it to a file in [non-realtime](https://doc.sccode.org/Guides/Non-Realtime-Synthesis.html)  Any simple examples on this?

- Also there is a new supercollider VST [UGen](https://git.iem.at/pd/vstplugin) which basically allows using VST plugins in SC. Would it be possible to use this in Foxdot?

Thank you! :)

**Comment by Qirky** [comment]
It's not possible to record anything in non-realtime I'm afraid - it's a language purely for live coding. You can - of course - prepare a piece of music in FoxDot and record the output in SuperCollider but obviously this takes the same amount of time to record as play. 

FoxDot can trigger any SynthDef stored in SuperCollider - it just has a small library of custom synths for convenience. So if you create a SynthDef in SuperCollider with this new UGen, you can trigger it as you would any other synth but you will need to add a few things to combine it with the effects chain. See https://foxdot.org/docs/using-your-own-synthdefs/ for more. Hope this helps!
