### ISSUE TITLE
Documentation for valid ranges?

### ISSUE THREAD

**Issue by sandcobainer** [Qirky/FoxDot#233]
Qirky,

First off this is an amazing open-source tool for performance and research. Thanks for this. I have been looking for some centralized documentation that details valid ranges for all the Player attributes. The documentation does mention some attributes and their ranges. 
For example: amp is valid between 0 to 1, but values above 1 maybe used with a risk of distortion is mentioned in the documentation. 
I am looking for a similar yet complete list of all attributes and their valid ranges. Is this how the parsing takes place under the hood?

**Comment by Qirky** [comment]
The only documentation is https://foxdot.org/docs/player-attributes/ and https://foxdot.org/docs/player-effects/. In theory any value is "valid" as it just gets passed to SuperCollider as it is input and doesn't parse it apart from converting strings of samples to buffer numbers. If you want to get under the hood you could take a look at the SuperCollider synth defs and how they are built and the ranges suggested in the UGen documentation there. Anything else is listed as best as possible in those links

**Comment by sandcobainer** [comment]
@Qirky Thank you, that gives me a better idea of the issues I'm seeing on a generative piece. I had difficulty figuring out what made some really disturbing sounds in the middle of the performance. 

It turned out to be a negative value being passed to a Low pass filter. From a design POV, do you think FoxDot requires a validation system similar to converting sample strings to buffer numbers?

**Comment by sandcobainer** [comment]
@Qirky I figured I was reaching the limits of FoxDot while tweaking it to my requirement. Your response validates my earlier suspicions.
I have been using FoxDot as a platform for a generative system in traditional music. I think the best way to do this might be to keep all my changes in an interface wrapper above FoxDot. That way, I wouldn't have to further change any design decisions or run into further challenges within FoxDot.

Something like Atom-FoxDot(parser system) -> FoxDot -> SuperCollider. Thank you for the detailed repsonse and FoxDot ofcourse!
