### ISSUE TITLE
FoxDot requiere Tkinter

### ISSUE THREAD

**Issue by gagarine** [Qirky/FoxDot#235]
This problem was already mentioned in #49 but I didn't find the FAQ. Or better, FoxDot could have also a nicer error message guiding the user to install Tkinter.

On MacOS the library can be installed with macport like that:

`sudo port install py-tkinter`

It come with the default option if you use brew.

**Comment by Qirky** [comment]
Fair enough, the FoxDot webpage does say the FAQ is in the discussion forum but it's not as clear as it used to be when it was on the site itself. I'll add Tkinter as a requirement on the README and installation
