### ISSUE TITLE
Documentation offline

### ISSUE THREAD

**Issue by bjrne** [Qirky/FoxDot#238]
I was about to look up something in the documentation of foxdot, however the website seems to be under a major rewrite. Luckily, parts of the website were saved by the wayback machine, however not all subpages of the documentation.

It would be of immense help if the old website would temporarily be made available, either on a different domain or here on github maybe? Another possibility would be to paste the documentation content into a Github wiki here in the repo.

Looking forward to the new website!

**Comment by Qirky** [comment]
Hi bjrne - I can understand your frustration but unfortunately my previous hosting plan expired before I was able to finish the site I'm currently working on. I've downloaded the documentation files but they aren't formatted correctly. I am currently in the process of formatting these and uploading to the site and it should be up and running in the next few days. Apologies for the inconvience

**Comment by bjrne** [comment]
Alright, thanks for the quick response and the great support of this project overall!

**Comment by Qirky** [comment]
Hi @bjrne just a heads up the alpha version of the new site is up with documentation
