### ISSUE TITLE
Midi problem

### ISSUE THREAD

**Issue by tesla9** [Qirky/FoxDot#239]
I have a problem with midi, I am sure it was working previously on my Mac, but now both on Mac and Raspberry Pi I've got same error:

>>> FoxDot.midi
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/FoxDot/lib/Code/main_lib.py", line 155, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 1, in <module>
    from __future__ import absolute_import, division, print_function
AttributeError: '_util' object has no attribute 'midi'

Midi works perfectly in SuperCollider on both mentioned devices.

**Comment by Qirky** [comment]
It looks like you're running the code `FoxDot.midi` in the FoxDot editor where it should be run in SuperCollider. You can find the documentation on the subject here: https://foxdot.org/docs/setting-up-midi/

Thanks :)
