### ISSUE TITLE
FoxDot not recognizing new sample 

### ISSUE THREAD

**Issue by abatugo** [Qirky/FoxDot#24]
Hello! I recently tried putting in a sample I created into one of the preexisting snd folders however, even after restarting, FoxDot still does not recognize the new sample. I converted my samples into .wav files as well. Do you know why it may not be working? Thanks!

**Comment by Qirky** [comment]
Hi abatugo - couple of questions that might help:

- Have you changed the "sample" keyword argument i.e. `bd >> play("x", sample=1)`
- Have you restarted SuperCollider?
- Do you have the most up-to-date version of FoxDot? Try `pip install FoxDot --upgrade` from the command line if you're not sure

If you've done all these and are still having the problem - let me know

**Comment by abatugo** [comment]
I tried all the above and I even rebooted my laptop. I think it may have to do with the way I converted into a .wav file. I could also try converting it again. Does FoxDot only recognize .wav files? Can the sample be mp3's or other file formats?

**Comment by Qirky** [comment]
I've found mp3 files don't always work with SuperCollider with me and I often get this error:

`File '../../audio.mp3' could not be opened: File contains data in an unknown format.`

Do you get this error in SuperCollider? You say you also have problems with .wav files? Which `snd` folder are you putting  the .wav file into?
