### ISSUE TITLE
ModuleNotFoundError: No module named 'lib'

### ISSUE THREAD

**Issue by jritch** [Qirky/FoxDot#25]
I'm getting the following error message when I try to run FoxDot on Python 3.6.0  (Anaconda 4.3.1 (x86_64)) on macOS 10.12.3:

jritchie$ pip install foxdot
Collecting foxdot
  Downloading FoxDot-0.3.2.zip (31.9MB)
    100% |████████████████████████████████| 31.9MB 21kB/s 
Building wheels for collected packages: foxdot
  Running setup.py bdist_wheel for foxdot ... done
  Stored in directory: /Users/jritchie/Library/Caches/pip/wheels/81/21/e4/b86c6b1fa1a2a88cd4707f52ba4cd5e60d97d7297b558394ef
Successfully built foxdot
Installing collected packages: foxdot
Successfully installed foxdot-0.3.2

jritchie$ python -m FoxDot
Traceback (most recent call last):
  File "/Users/jritchie/anaconda/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/jritchie/anaconda/lib/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/jritchie/anaconda/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/Users/jritchie/anaconda/lib/python3.6/site-packages/FoxDot/__init__.py", line 11, in <module>
    from lib import *
ModuleNotFoundError: No module named 'lib'

**Comment by jritch** [comment]
Ah, I was supposed to use Python 2.7 - now it works

Still I think a better error message for people who try using Python 3 would be helpful (or even better, not let pip install the package for Python 3 at all, if that's possible?)

**Comment by Qirky** [comment]
Hi jritch - I will definitely add this to the next build. I'm hoping to make FoxDot python 3 compatible this summer also.

**Comment by shamansir** [comment]
@Qirky Is there a way to track when that will happen [or not]? :)

**Comment by Qirky** [comment]
I've recently created a twitter account for FoxDot, https://twitter.com/FoxDotCode, where I'll be announcing features etc so keep an eye on that :)

**Comment by shamansir** [comment]
@Qirky Thank you! Got it running under Python 2.7 and Conda for now.

**Comment by Qirky** [comment]
Great to hear! Just to keep you updated, I've nearly updated FoxDot for Python 3 and should hopefully publish it before the end of the week.
