### ISSUE TITLE
`www.foxdot.org`  DNS entry does not exists

### ISSUE THREAD

**Issue by RobertBendun** [Qirky/FoxDot#250]
FoxDot editor links to tutorials through `www.foxdot.org` but only `foxdot.org` is defined

```console
$ dig +short www.foxdot.org
$ dig +short foxdot.org
138.68.191.187
```

https://github.com/Qirky/FoxDot/blob/76a4e3ad31a987c6e2c43c38d0440898d3408780/FoxDot/lib/Workspace/Editor.py#L1779-L1785

**Comment by Qirky** [comment]
Ahh good spot - I hadn't set up the DNS records quite right when I set up the new site, thanks. `www` should be working now. However the docs url is incorrect, so will need to update that in the code

**Comment by sutyrin** [comment]
It seems to work perfectly: 

https://www.whatsmydns.net/#A/www.foxdot.org
