### ISSUE TITLE
function or tool to keep integers?

### ISSUE THREAD

**Issue by qantuum** [Qirky/FoxDot#253]
sometimes I work with patterns and try to obtain surprising patterns generators to use in my players. The problem, these patterns often end up non-integer, which results in being not in tune with the built-in quantitizer (Scale.default.set).

So I'd like to know how can I use the python int(x) function in patterns? So I can take all my non-integers, turn them into integers.

Cheers,

**Comment by Qirky** [comment]
Sure, you can use the `transform` method for `Pattern` or `GeneratorPattern` instances to essentially apply a function to all the values e.g.

```python
>>> generator = PWalk() / 2
>>> print(generator[:10])
P[0.0, -0.5, -1.0, -1.5, -1.0, -1.5, -1.0, -1.5, -2.0, -2.5]
>>> generator = generator.transform(int)
>>> print(generator[:10])
P[0, 0, -1, -1, -1, -1, -1, -1, -2, -2]
```

**Comment by qantuum** [comment]
thanks, that's pretty cool, I'll try other math functions from python too..
