### ISSUE TITLE
Oops, something went wrong!

### ISSUE THREAD

**Issue by david-dunkley** [Qirky/FoxDot#257]
Hi,

I tried to create an account on the FoxDot site and received the message listed in the header. 
I teach music, math, CS, and coding using Earsketch, Turtle, TunePad, and wanted to incorporate a live-based Python coding class as well. I found FoxDot while looking at Sonic Pi and wanted to use FoxDot if possible. Is FoxDot being actively maintained? 
Best,
David

**Comment by qantuum** [comment]
I find a lot of Error 404's on foxdot website, including documentation and forum.
For some reason those parts of the website have been down...
Interested to see if a solution will be offered.

**Comment by Qirky** [comment]
Hi both, FoxDot isn't being actively maintained but the website is still up. The mysql database occasionally falls over and needs restarting like in this case so it's helpful to get notified by the community. Site should be working fine now

**Comment by qantuum** [comment]
thanks so much! I missed the documentation dearly.
