### ISSUE TITLE
FoxDot 0.3.5 overeating cpu on Linux

### ISSUE THREAD

**Issue by jarbowski** [Qirky/FoxDot#26]
Hi,
With this new version, python is overeating cpu at launch and FoxDot is not usable at all.
No usefull information with python -v -m FoxDot
This happens on Debian Sid (SC 3.7) and Void Linux (SC 3.8).
0.3.4 works well on both systems.

What do you think?

Thanks

**Comment by Qirky** [comment]
Hi Jarbowski,

This is likely because I changed the sleep time variable in `TempoClock.py`. Do you install from pip or from this repo? I've updated the file here if you want to do a fresh install of v0.3.5 and see if that helps.

**Comment by jarbowski** [comment]
I installed it from pip but I updated the file:
Everythink is okay now.
Thank you very much!
