### ISSUE TITLE
Using hpf and hpr attributes makes gibberish sound with intense volume jumps

### ISSUE THREAD

**Issue by qantuum** [Qirky/FoxDot#260]
This is a fact well-known in the community that formed around this app over the years, but I still see no warning in official FoxDot documentations by Qirky, so I thought it could be useful to raise the issue.

I really don't know why this happens.

Something as simple as the string below can transform my computer into a screeching banshee

`uu >> pads(P[0,1,2],hpf=1200,hpr=300)`

Actually, what are the numbers in these parameters, are they values in Hertz like in other software filters?

**Comment by Qirky** [comment]
It's listed in the documentation here: https://foxdot.org/docs/player-effects/

`hpr` and `lpr` should normally be values between 0 and 1. From the docs:

> You can also set the high-pass resonance for the filter using the hpr keyword. This is sometimes referred to as “rq” or “hpq”. As this value decreases, the overtones near the cutoff value are boosted – a value close to 0 will sound like a sine wave oscillating at the value set using hpf. **Be careful of very small and very large values as you might get very loud sounds!**

**Comment by qantuum** [comment]
I don't understand why very small values would make a loud sound, isn't resonance a boost to the cutoff frequency?
What exactly is the number doing?

Though I recognize now that I have no idea why I thought a value of 300 would be a good idea.
