### ISSUE TITLE
404 tutorials & doc

### ISSUE THREAD

**Issue by sachaz** [Qirky/FoxDot#263]
Hi,
broken links for the getting started & tutorial/doc from foxdot.org

**Comment by egndz** [comment]
seems like there is an issue with the server. I cannot ping https://foxdot.org/docs/making-your-first-sounds/.

However, you can try:

Install Sphinx, a tool for creating documentation. You can install it using pip:
`pip install sphinx` 
Navigate to the docs directory in your project:
`cd docs`
Run the Makefile to generate the documentation. If you're on a Unix-like system (like Linux or MacOS), use:
`make html`
If you're on Windows, use:

`make.bat html`

This will generate a set of HTML files in a _build/html directory. You can open the index.html file in a web browser to view your local documentation.

**Comment by Qirky** [comment]
Looks like MySQL crapped out so I set up a new DB from a backup. Site should be back up now and more stable

**Comment by slavanorm** [comment]
You could have moved to github pages if the site was static html/js, without cms stuff
