### ISSUE TITLE
Player and Time var

### ISSUE THREAD

**Issue by jarbowski** [Qirky/FoxDot#27]
hi,

p1 >> play("a",sample=var([0,1,2,3],[1]))
is equal to
p1 >> play("a",sample=var([0,1,2,3],[1]),dur=1/2)

but
p1 >> play("a",sample=var([0,1,2,3],[1]),dur=1)
works as expected

**Comment by Qirky** [comment]
Hi Jarbowski, I'm afraid I don't quite understand what the problem is - could you clarify?

**Comment by jarbowski** [comment]
I got confused between synth and player.
Sorry for the useless annoyance.

**Comment by Qirky** [comment]
Haha no problem :)
