### ISSUE TITLE
sc3-plugins not loaded

### ISSUE THREAD

**Issue by jarbowski** [Qirky/FoxDot#30]
Hi,
I updated today to 0.4.5 via pip and now FoxDot won't find sc3-plugins.
A strange thing too: print SynthDefs shows a syntax error in the console

PS: the new loop synth is absolutely awesome!)

**Comment by Qirky** [comment]
Have you opened the interface gone to Code -> Use SC3 Plugins? Now that FoxDot has been updated to work with Python 3 you'll need to use Python 3 print syntax which just means using brackets like so:

`print(SynthDefs)`

As usual, not been great updating the docs on that!

**Comment by jarbowski** [comment]
Yes I did.
Still
*** ERROR: SynthDef piano not found
FAILURE IN SERVER /s_new SynthDef not found
in the SC console.
And no piano synth with print(SynthDefs)

**Comment by jarbowski** [comment]
Just to check my system I downgraded to 0.3.9 and it works.

**Comment by Qirky** [comment]
I somehow deleted the all important `piano.add()` when defining the SynthDef so should be fine now if you are working from this rep

**Comment by jarbowski** [comment]
Everything is okay.
Thanks
