### ISSUE TITLE
[REQUEST] feature to recover unsaved work

### ISSUE THREAD

**Issue by Chovin** [Qirky/FoxDot#34]
Often times I'm playing about experimenting and end up crashing FoxDot various ways only to find that in the heat of things, I didn't save.

Having a feature to automatically save file changes to a separate directory that we could recover from, visible or invisible to the user would be awesome.

**Comment by Qirky** [comment]
Yeah, good idea. Will definitely add this to the next update

**Comment by Qirky** [comment]
Have added this feature in the last repo update, if you could give it a go and see how it works for you and let me know that'd be great

**Comment by Chovin** [comment]
Thank you! 
I'll be able to do so in a few weeks. sorry, slammed with other stuff.

**Comment by Chovin** [comment]
Awesome! Seems to work pretty reliably. The window gets stuck though. It seems like I need to open another modal window, like saving or opening another file for it to go away
![image](https://user-images.githubusercontent.com/17536161/31545538-321cfdde-b063-11e7-85bf-9957ae95042c.png)

**Comment by Qirky** [comment]
Can you test this with the latest version and let me know if you still have the same issue.

**Comment by JustDef** [comment]
Same problem here.
osx 
foxdot latest ver
Python 2.7

**Comment by Qirky** [comment]
Apparently it's caused by calling popup windows before the "mainloop" so in this last commit I've set the "recover work popup" function to be called 0.1ms after startup to see if it stops crashing. If you could let me know if you still get the error that'd be great.

**Comment by Justabaloon** [comment]
Just tested it and now it seems to work without issues.
