### ISSUE TITLE
Undo Buffer Is Overwritten by `every`

### ISSUE THREAD

**Issue by Miserlou** [Qirky/FoxDot#42]
I think that's what's happening - I can't cmd+Z any more because I have an `every` loop eating it up, I think.

**Comment by Qirky** [comment]
Thanks for catching this. I'm assuming it's a samples pattern and the string changes when the function is called in the `every` loop? I'm thinking of removing the strings that change in place, or at least until I improve how they're used. In the next update I'll remove them and then undo should work again.
