### ISSUE TITLE
Real Documentation

### ISSUE THREAD

**Issue by Miserlou** [Qirky/FoxDot#44]
So - this is probably the big one. I really want to dive in pretty deep with this project, but it seems like other than watching you jam on YouTube, there really isn't a good way to learn FoxDot yet.

The `docs` folder really reads like a javadoc, etc - it's a reference for (some of) the API - but not _documentation_ in any human-readable sense.

I know it's a big undertaking, and often the least fun part of a project, but I think you should try to make this a primary issue for a little while.

I actually think your current approach in the README file is perfect, I'm a huge fan of massive READMEs myself, I'd just love it if you could show a lot more advanced usage which exhausts the feature space of FoxDot.

**Comment by Chovin** [comment]
For now there's some good stuff in https://github.com/Qirky/FoxDot/tree/master/Tutorial as well
Qirky is pretty active (sorry Qirky :3) in the Live coding slack channel as well https://toplap.org/toplap-on-slack/

**Comment by Qirky** [comment]
The project changed quite a bit early on so documentation was always behind so I've decided to generate the docs from inline docstrings, which will include more descriptive documentation (see the [Players](https://github.com/Qirky/FoxDot/blob/master/docs/Players.md) docs for an idea of this). It's just finding the time to do this.

**Comment by ianb** [comment]
I'll say that the *funnest* documentation would be for FoxDot to open up with code that demonstrates lots of things, with comments to explain, and then you'd start executing statements and seeing what they sound like.

Though having a third Help pane to the editor could also be cool.
