### ISSUE TITLE
Pwrand not defined in Players.py

### ISSUE THREAD

**Issue by ianb** [Qirky/FoxDot#45]
The exception is pretty self-explanatory:

```py
>>> p >> pads([11, 10, 9, 13], room=0.5).degrade()
Traceback (most recent call last):
  File "/Users/ianbicking/.virtualenvs/foxdot/lib/python2.7/site-packages/FoxDot/lib/Code/main_lib.py", line 106, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "/Users/ianbicking/.virtualenvs/foxdot/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 313, in __rshift__
    getattr(self, method).__call__(*args, **kwargs)
  File "/Users/ianbicking/.virtualenvs/foxdot/lib/python2.7/site-packages/FoxDot/lib/Players.py", line 1467, in degrade
    self.amp = Pwrand([0,1],[1-amount, amount])
NameError: global name 'Pwrand' is not defined
```

**Comment by Qirky** [comment]
Thanks, that's been sorted now.

**Comment by Chovin** [comment]
so ummm
what's PwRand? :3

**Comment by Qirky** [comment]
It's a weighted random number generator. `PRand` chooses values from a list where all values are weighted equally (i.e. equal chance of being chosen) and `PwRand` chooses values from a list where some values are more likely than others to be selected. Example

`PwRand([0,1,2],[1,5,10])`

This is 5 times for likely to return a 1 than a 0 and 10 times more likely to return a 2 than a 0 - and therefore twice as likely to return a 2 than a 1. When you use the `degrade` method, it creates a `PwRand` to change the weights of selecting a 1 or 0 for amplitude of the Player. The automatically Generated documentation for PatternGenerators is especially poor as they are subclasses of `Random` and all the inherited methods are included in the documentation. Hope that helps.
