### ISSUE TITLE
Keyboard shortcuts mislabeled on Mac

### ISSUE THREAD

**Issue by ianb** [Qirky/FoxDot#46]
Under the Code menu: "Evaluate block" is labeled as ^-Enter, but is actually Cmd-Enter, and "Evaluate Line" is labeled as Option-Enter, but I can't figure out what the actual keyboard shortcut is. "Clear scheduling clock" is also labeled as ^. but is actually Cmd-.

**Comment by Qirky** [comment]
Very strange - I assumed it would just display the string "Ctrl+Return". The "Evaluate Line" is "Alt-Return" on Windows, what is the  equivalent on a Mac?

**Comment by joesh1** [comment]
Also Ctrl+K doesn't produce any help .....

**Comment by Qirky** [comment]
Hi Joe, does Cmd+K work? I think it's just mislabelled for Mac users which is an easy fix

**Comment by joesh1** [comment]
No, it doesn't, what do you think it is (should/could be) on a Mac?
