### ISSUE TITLE
Stopping a Player

### ISSUE THREAD

**Issue by Miserlou** [Qirky/FoxDot#47]
I have no idea how to stop a player, I see no documentation about this. I'm not sure if this is a bug or if I'm doing something wrong. If I delete a player from the environment and update, it just keeps going. I can't set it to `None`. I can set it to something else, but not to nothing. I was expecting that if I deleted it from the environment on screen, it would be set to None.

**Comment by Chovin** [comment]
you can stop a player assigned to `p1` by just eval-ing a `p1.stop()`.
For players I want to stop and start often I usually just tack a `.stop()` at the end of the player line that I can comment/uncomment whenever I want `p1 >> play('xx (-o) ')#.stop()`

if you ended up removing the reference to the player object somehow, you can always stop all the players with `ctrl+.` or you could look for the player in `Clock.players()` and stop it from there like so: `Clock.players()[0].stop()` (assuming it was the 1st player I wanted to stop)

**Comment by Qirky** [comment]
As Chovin said, you can use the `stop` method. This was in the Players.py documentation which is generated from the docstrings but was accidentally removed when making it compatible with Python 3. You can see some the updated information here: https://github.com/Qirky/FoxDot/blob/master/docs/Players.md
