### ISSUE TITLE
Python crashes everytime I run FoxDot :(

### ISSUE THREAD

**Issue by enzyme69** [Qirky/FoxDot#52]
Keep getting this crashing message... any idea?

![screen shot 2017-10-31 at 12 16 14](https://user-images.githubusercontent.com/3952687/32203135-619d6c1c-be35-11e7-8bca-71f9edaa8044.png)

**Comment by enzyme69** [comment]
Also this message:
'ConnectionRefusedError' object is not subscriptable

Appears non stop then crashed.

**Comment by enzyme69** [comment]
2017-10-31 14:45:09.326 python[1142:66687] -[TKWindow setCanCycle:]: unrecognized selector sent to instance 0x116d39260
2017-10-31 14:45:09.340 python[1142:66687] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[TKWindow setCanCycle:]: unrecognized selector sent to instance 0x116d39260'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010010b53b __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x0000000100db9942 objc_exception_throw + 48
	2   CoreFoundation                      0x00000001001a2824 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
	3   CoreFoundation                      0x0000000100082f13 ___forwarding___ + 1443
	4   CoreFoundation                      0x00000001000828e8 _CF_forwarding_prep_0 + 120
	5   libtk8.5.dylib                      0x0000000110d71f9f ApplyWindowAttributeFlagChanges + 1124
	6   libtk8.5.dylib                      0x0000000110d72aa8 TkMacOSXApplyWindowAttributes + 51
	7   libtk8.5.dylib                      0x0000000110d72f86 TkMacOSXMakeRealWindowExist + 1189
	8   libtk8.5.dylib                      0x0000000110d74112 WmIconbitmapCmd + 226
	9   libtk8.5.dylib                      0x0000000110d75574 Tk_WmObjCmd + 1935
	10  libtcl8.5.dylib                     0x0000000110bbfa47 TclEvalObjvInternal + 773
	11  libtcl8.5.dylib                     0x0000000110bc0aa5 Tcl_EvalObjv + 66
	12  _tkinter.cpython-35m-darwin.so      0x0000000110ba7bed Tkapp_Call + 189
	13  libpython3.5m.dylib                 0x00000001007b39d9 PyCFunction_Call + 233
	14  libpython3.5m.dylib                 0x0000000100840cd7 PyEval_EvalFrameEx + 36647
	15  libpython3.5m.dylib                 0x0000000100841900 _PyEval_EvalCodeWithName + 2400
	16  libpython3.5m.dylib                 0x000000010083fc75 PyEval_EvalFrameEx + 32453
	17  libpython3.5m.dylib                 0x0000000100841900 _PyEval_EvalCodeWithName + 2400
	18  libpython3.5m.dylib                 0x0000000100841a07 PyEval_EvalCodeEx + 71
	19  libpython3.5m.dylib                 0x000000010078e6ba function_call + 186
	20  libpython3.5m.dylib                 0x0000000100759e63 PyObject_Call + 99
	21  libpython3.5m.dylib                 0x000000010077712c method_call + 140
	22  libpython3.5m.dylib                 0x0000000100759e63 PyObject_Call + 99
	23  libpython3.5m.dylib                 0x00000001007cccc1 slot_tp_init + 81
	24  libpython3.5m.dylib                 0x00000001007c7964 type_call + 212
	25  libpython3.5m.dylib                 0x0000000100759e63 PyObject_Call + 99
	26  libpython3.5m.dylib                 0x0000000100839b9c PyEval_EvalFrameEx + 7660
	27  libpython3.5m.dylib                 0x0000000100841900 _PyEval_EvalCodeWithName + 2400
	28  libpython3.5m.dylib                 0x0000000100841a61 PyEval_EvalCode + 81
	29  libpython3.5m.dylib                 0x000000010083526f builtin_exec + 623
	30  libpython3.5m.dylib                 0x00000001007b39d9 PyCFunction_Call + 233
	31  libpython3.5m.dylib                 0x0000000100840cd7 PyEval_EvalFrameEx + 36647
	32  libpython3.5m.dylib                 0x0000000100841900 _PyEval_EvalCodeWithName + 2400
	33  libpython3.5m.dylib                 0x000000010083fc75 PyEval_EvalFrameEx + 32453
	34  libpython3.5m.dylib                 0x0000000100841900 _PyEval_EvalCodeWithName + 2400
	35  libpython3.5m.dylib                 0x0000000100841a07 PyEval_EvalCodeEx + 71
	36  libpython3.5m.dylib                 0x000000010078e6ba function_call + 186
	37  libpython3.5m.dylib                 0x0000000100759e63 PyObject_Call + 99
	38  libpython3.5m.dylib                 0x00000001008883b1 RunModule + 161
	39  libpython3.5m.dylib                 0x0000000100889006 Py_Main + 2310
	40  python                              0x0000000100000e92 main + 418
	41  python                              0x0000000100000cc4 start + 52
	42  ???                                 0x0000000000000003 0x0 + 3
)
libc++abi.dylib: terminating with uncaught exception of type NSException
Abort trap: 6

**Comment by enzyme69** [comment]
Loading SynthDef from /Users/jimmygunawan/anaconda/envs/py33/lib/python3.5/site-packages/FoxDot/osc/scsyndef/dub.scd
Loading SynthDef from /Users/jimmygunawan/anaconda/envs/py33/lib/python3.5/site-packages/FoxDot/osc/scsyndef/viola.scd
Loading SynthDef from /Users/jimmygunawan/anaconda/envs/py33/lib/python3.5/site-packages/FoxDot/osc/scsyndef/scratch.scd
Loading SynthDef from /Users/jimmygunawan/anaconda/envs/py33/lib/python3.5/site-packages/FoxDot/osc/scsyndef/klank.scd
ERROR: Class not defined.
  in file 'selected text'
  line 8 char 13:

  osc=Decimator.ar(osc, bits: (rate - 1));
               
  env=EnvGen.ar(Env(curve: 'lin',levels: [0, amp, 0],times: (sus * 2)), doneAction: 0);
-----------------------------------
Loading SynthDef from /Users/jimmygunawan/anaconda/envs/py33/lib/python3.5/site-packages/FoxDot/osc/scsyndef/ambi.scd
Loading SynthDef from /Users/jimmygunawan/anaconda/envs/py33/lib/python3.5/site-packages/FoxDot/osc/scsyndef/glass.scd
Loading SynthDef from /Users/jimmygunawan/anaconda/envs/py33/lib/python3.5/site-packages/FoxDot/osc/scsyndef/soft.scd

**Comment by enzyme69** [comment]
I am running this on Python 3, Anaconda environment bundle.

If I am running it using Python 2, it seems to work. I tried python3 -m FoxDot -> failed.

**Comment by Qirky** [comment]
I'm fully clued up on using Anaconda but the error seems similar to the one discussed [here](http://flothesof.github.io/sms-tools-MacOSX-Anaconda.html#disqus_thread) and [here](https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/y1UWpFHsDyQ) which suggests there is a problem with `matplotlib` (not used by FoxDot) and Anaconda. There are no advantages of using FoxDot with Python 3 so if it works using Python 2 then I'd suggest doing that for the time being. Other possible solutions would be to update the version of Tcl/Tk in Anaconda (see links above) adding the following two lines into `FoxDot.lib.__init__`:

```python
import matplotlib
matplotlib.use('TkAgg')
```

If you do try this could you let me know if the problem persists? As for the second issue - `Class not defined` in SuperCollider - this is can be fixed by opening the FoxDot editor and going to the "Code" menu and de-selecting "Use SC3 Plugins". This has since been set to False by default. Do you know what version of FoxDot you are using?

**Comment by nf2111** [comment]
I had the same issue. (I was running FoxDot on Python 3, Anaconda environment bundle)

however, I installed python 3.6.4 

```
pyenv install 3.6.4
```

installed FoxDot
```
pip install FoxDot
```

started FoxDot
```
python -m FoxDot
```
finally it worked fine.

**Comment by alexanderwuque** [comment]
I reinstalled matplotlib by running `conda install matplotlib` and it worked. See [https://stackoverflow.com/questions/31373163/anaconda-runtime-error-python-is-not-installed-as-a-framework/44912322#44912322](url).
