### ISSUE TITLE
Workshop troubleshooting suggestions (ubuntu)

### ISSUE THREAD

**Issue by DavidS48** [Qirky/FoxDot#53]
Hi! We found a few issues on the workshop on Thursday that might be worth documenting the workarounds for. None of them are actually FoxDot problems, but I think that two or three people hit each of them independently.

Setup: Ubuntu 14.04, SuperCollider 3.6.6, Jackd 0.122.0.

Problem:  SuperCollider won't load the quark
Solution:
Put FoxDot.sc (from the github repo) in
/usr/share/SuperCollider/SCClassLibrary/
recompile class library

Problem: FoxDot.sc code loads and runs, FoxDot starts and connects, but there's no sound output. The QjackCtl Connect window's Audio tab shows no outputs available.
Solution: Go to QjackCtl's Setup window and change the "output" setting until you get the right device for your soundcard.

Another thing that might be worth mentioning is that if Supercollider or Jack falls over, you need to stop everything and start them again in order - just restarting Supercollider doesn't work because FoxDot doesn't know that it needs to resend the stuff it sends on loading.

Cheers!

**Comment by Qirky** [comment]
Hi  David, thanks for this. I've updated the [FAQ page](http://foxdot.org/index.php/forum/?view=thread&id=1) and added a thank you in the README. Cheers.
