### ISSUE TITLE
(linux) _tkinter.TclError: bad event type or keysym "#"

### ISSUE THREAD

**Issue by claudeha** [Qirky/FoxDot#6]
I commented out this line in FoxDot/Interface/Editor.py and got it working:

        self.text.bind("<{}-#>".format(ctrl),               self.toggle_console

Naturally this breaks that feature.  Tested on GNU/Linux Debian Jessie.

**Comment by Qirky** [comment]
Hi Claude, this error is now caught and used the keyboard shortcut "Ctrl+T" to toggle the console. If you can confirm this works on Linux that would be very helpful, thanks.

Ryan

**Comment by claudeha** [comment]
Yes works fine, thanks.
