### ISSUE TITLE
Synths build up eventually stopping sound

### ISSUE THREAD

**Issue by Chovin** [Qirky/FoxDot#65]
leaving this running causes the number of synths to go up forever eventually stopping all sound
```py
p2 >> piano([6], dur=PDur(5,8), 
            amp=var([.2,.6], 16), 
            lpf=var([100,1200],6), 
            hpf=var([1400, 200], 10))
```

**Comment by Qirky** [comment]
I've changed the "output" SynthDef to force the synth to release after 8 times their sustain value. It's a bit of a hacky workaround but kills the synths here.
