### ISSUE TITLE
OSCClient(("localhost", 8000)) -> ValueError: 'server' argument is not a valid OSCServer object

### ISSUE THREAD

**Issue by Chovin** [Qirky/FoxDot#66]
wanted to try out the new OSC stuff but got this:
```py
DefaultServer.forward = OSCClient(("localhost", 8000))
Traceback (most recent call last):
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/Code/main_lib.py", line 106, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/OSC3.py", line 1060, in __init__
    self.setServer(server)
  File "/Users/Chovin/Projects/LiveCoding/FoxDot/FoxDot/FoxDot/lib/OSC3.py", line 1096, in setServer
    raise ValueError("'server' argument is not a valid OSCServer object")
ValueError: 'server' argument is not a valid OSCServer object
```

**Comment by Qirky** [comment]
My apologies - I have an incorrect example in the README. The correct way to use an OSCClient object is to create it then call the "connect" method e.g.

```
myClient = OSCClient()
myClient.connect(("localhost", 8000))
DefaultServer.forward = myClient
```

For the time being you can use a subclass I created called `OSCConnect` which takes the address argument in the constructor e.g. `DefaultServer.forward = OSCConnect(("localhost", 8000))` although I might set the `forward` attribute to an unassigned OSCClient that you can connect at runtime using the following syntax: `DefaultServer.forward.connect(("localhost", 8000))`.
