### ISSUE TITLE
Reset effects if kwarg not present

### ISSUE THREAD

**Issue by Psykopear** [Qirky/FoxDot#68]
In FoxDot if you first define a synth let's say

`s1 >> varsaw(0, room=1, mix=1)`

and then you evaluate it again without room and mix parameters

`s1 >> varsaw(0)`

the mix and room parameters will stay at 1 unless you explicitly specify them to be 0. 
I was wondering if that's the intended behaviour, otherwise I can work to make it reset effects params if kwargs are not present (if instead this is intended, I will see if I can add it as an opt in behaviour).

**Comment by Qirky** [comment]
This is intended to allow attributes to be changed outside of the `>>` system e.g. using `Group(s1, s2).hpf=5000` or similar. If I updated `s1` it would remove the high pass filter I just applied. One way to get around things is to call the `reset` method before you update a player:

```python
s1.reset()
s1 >> varsaw(0, room=1, mix=1)

s1.reset()
s1 >> varsaw(0)
```

This will remove all effects then apply those in brackets. Happy to hear about alternatives tho!

**Comment by Psykopear** [comment]
Ok, I didn't see the reset method, I think that's enough. You can close the issue.

**Comment by Qirky** [comment]
Also realised you can do it in one line: `p1.reset() >> pluck()`
