### ISSUE TITLE
SynthDefs and SynthDef are undefined

### ISSUE THREAD

**Issue by dospunk** [Qirky/FoxDot#70]
When I try to do anything with SynthDef or SynthDefs I get a name error. SuperCollider isn't playing any noise either because of the same error.

I'm on Windows 10 running Python 3

**Comment by Qirky** [comment]
Hi dospunk, have you evaluated the line `FoxDot.start` in SuperCollider? Could you copy and paste the error text here? Thanks

**Comment by dospunk** [comment]
I have evaluated `FoxDot.start` in SC

When I evaluate `print(SynthDefs)` in FoxDot I get this message
```
>>> print(SythDefs)
Traceback (most recent call last):
  File "C:\Users\Connor\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\Code\main_lib.py", line 106, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 1, in <module>
    """
NameError: name 'SythDefs' is not defined
```
If I evaluate
```py
p1 >> pads([0, 1, 2, 3])
d1 >> play("x-o-")
```
I don't get any error in FoxDot, but I get these errors repeated in SC 
```
*** ERROR: SynthDef makeSound not found
FAILURE IN SERVER /s_new SynthDef not found
```
```
*** ERROR: SynthDef startSound not found
FAILURE IN SERVER /s_new SynthDef not found
```
```
*** ERROR: SynthDef play2 not found
FAILURE IN SERVER /s_new SynthDef not found
```
```
*** ERROR: SynthDef pads not found
FAILURE IN SERVER /s_new SynthDef not found
```
```
*** ERROR: SynthDef play1 not found
FAILURE IN SERVER /s_new SynthDef not found
```

**Comment by Chovin** [comment]
you're missing an `n` in `SynthDefs` in that `print(SynthDefs)` output.

as for the `*** ERROR: SynthDef makeSound not found` errors,
I get those every so often. A restart of SuperCollider (and `FoxDot.start`) followed by a restart of FoxDot usually does the trick 👍

**Comment by dospunk** [comment]
I think the problem was I was starting FoxDot (the program) before running `FoxDot.start` in SC because I got a bunch of output this time that I never got before. Also thanks for pointing out the typo, but I'm pretty sure that wasn't it because I checked it multiple times the first time I had the problem

**Comment by Qirky** [comment]
Glad it's sorted - I'll make sure it's clear in the set up instructions to start SuperCollider *before* FoxDot. Cheers.
