### ISSUE TITLE
FoxDot is a package and cannot be directly executed 

### ISSUE THREAD

**Issue by benithebread** [Qirky/FoxDot#75]
Hi there, I'm using an MBP 2017 13'' with Sierra (10.12.6), installed homebrew to have python3 and installed FoxDot via pip3. When trying to execute it, I get his error message:

`Benjamins-MBP:~ benji$ python3 -m FoxDot
/Library/Frameworks/Python.framework/Versions/3.6/bin/python3: No module named FoxDot.__main__; 'FoxDot' is a package and cannot be directly executed`
When trying to uninstall it (which also did not work), and randomly testing the same command again, I could get it to work. I was shocked and turned it off. I was intending to start SuperColliders FoxDot to get into jamming. 
But after trying the same command again I got the same response. Any ideas what I could do?

Thank you guys, FoxDot looks really cool, I would love to make it work

**Comment by Chovin** [comment]
just curious, do you happen to have a FoxDot folder in your home directory? `~`

**Comment by benithebread** [comment]
yes I do, might that help my case somehow?

**Comment by benithebread** [comment]
Also, I do find a file called `__main__.py` inside the folder. So I don't see why my python3 cannot find it?

**Comment by Chovin** [comment]
just out of curiousity, `cd` somewhere else like `Desktop`. somewhere without a FoxDot folder.
then try start FoxDot

**Comment by benithebread** [comment]
Chovin It works!
 
When I 'cd' to 'user/FoxDot', and than run 'python3 -m FoxDot', it runs the '__main__.py' file! So nice!

Thank you for your help! So cool :)

**Comment by Qirky** [comment]
Glad it's working - thanks Chovin. @benithebread was the user/FoxDot directory created when you installed using pip?

**Comment by benithebread** [comment]
@Qirky I think it was created by pip3, which was installed through homebrew. Homebrew does a lot of changes to the system, thus I think that if Ou installed your FoxDot via usually preinstalled python and pip, it migjt be in the system's lib

**Comment by Qirky** [comment]
Very strange - I'll make a note of it for the trouble shooting page. Thanks.
