### ISSUE TITLE
var issue after updated

### ISSUE THREAD

**Issue by pecco** [Qirky/FoxDot#77]
Everything works as usual but after update I cant play any `var` `linvar` etc...

` f1 >> klank(lpf=linvar([4000,60],16))
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\FoxDot\lib\Code\main_lib.py", line 110, in __call__
    exec(self._compile(code), self.namespace)
  File "FoxDot", line 2, in <module>
  File "C:\Python27\lib\site-packages\FoxDot\lib\TimeVar.py", line 36, in __init__
    Repeatable.__init__(self)
TypeError: unbound method __init__() must be called with Repeatable instance as first argument (got linvar instance instead)`

updated to FoxDot 0.5.4 from 0.5.2
Supercollider 3.8.0
Python 2.7

**Comment by Qirky** [comment]
Hi Pecco, thanks for catching this. I removed the dependency on the "Repeatable" class in the "TimeVar" class but did not remove the `Repeatable.__init__` which is causing the problem. Will be pushing v0.5.5 later today with the fix.

**Comment by pecco** [comment]
Thank you, it's working now! 👍
