### ISSUE TITLE
Bitcrush and Klank

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#79]
Hi Ryan, I notice that bitcrush and klank don't seem to be recognised - using a mac. Any suggestions? 

The SC post window just says (the usual):

> *** ERROR: SynthDef klank not found
> FAILURE IN SERVER /s_new SynthDef not found
> *** ERROR: SynthDef bitcrush not found
> FAILURE IN SERVER /s_new SynthDef not found

**Comment by Justabaloon** [comment]
Have you installed SC3 plugins?

**Comment by joesh1** [comment]
Plugins, which ones? I imagine klank/bitcrush are part of FoxDot (no?).

**Comment by Justabaloon** [comment]
http://foxdot.org/installation/

**Comment by joesh1** [comment]
Thanks, I had assumed that if it was in SC, FD was able to access them. Anyhow, just done the necessary stuff, however (although everything runs fine I imagine) one thing that still gets thrown up in the Terminal is this:

> objc[6737]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff87a16b68) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x119220cd8). One of the two will be used. Which one is undefined.

Do I need to replace of the bundles (and if so which)?

**Comment by Justabaloon** [comment]
Glad it worked.
About your last question... I'm sorry but i'm not able to help you.
Maybe it's better to open another "Issue" so it will be easy to find an answer by someone looking for the same problem in the future.

**Comment by joesh1** [comment]
Will do, thanks.
