### ISSUE TITLE
high CPU usage

### ISSUE THREAD

**Issue by claudeha** [Qirky/FoxDot#8]
FoxDot seems to use 100% of one core, even when idle.

**Comment by Qirky** [comment]
The TempoClock now sleeps for a short period of time (1 beat duration or until the next scheduled event, whichever is shorter) at each loop. If you could try this again and let me know about performance that would be great.

**Comment by claudeha** [comment]
CPU usage is tiny now, thanks!

**Comment by joesh1** [comment]
Hi Ryan, I find the CPU usage very high (still). I'm on a Mac (High Sierra), and surprised at how much my computer (laptop) keeps the fan going non-stop. I'm a SC user and have never seen this much CPU use, so I'm a little surprised. Any suggestions? 

BTW, the update to the help files is fantastic. I'd ask one more thing, wouldn't it be possible (one of these days) to be able to open multiple windows? .....(Just a thought)

**Comment by Qirky** [comment]
If you run `print(Clock.sleep_time)` you'll see the duration that the clock sleeps before checking if it's time to trigger the next event. You can change this to something bigger like so:

`Clock.sleep_time = 0.01`

This should reduce the CPU load but you won't be able to use very small or combine odd duration values. Could do a "high performance vs power saver" option I suppose

**Comment by joesh1** [comment]
Hi Ryan, I'll check that (sleep time is 0.0001, which seems a little short). Thanks.
