### ISSUE TITLE
events not behaving correctly

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#82]
Hi Ryan

Just playing around (whilst following the help videos) with the events. I notice if you type:
`p1.every(4, "stutter", 2)` this works, but if you continue with `p1.every(4, "stutter", 2, oct=3)` then the octave works, but not the stutter. I also tried `p1.every(4, "stutter", 2, oct=3, pan=[-1,1])`, but no luck, the octave command takes precedent!

I've tried it on Py2 and Py3, didn't seem to make any difference (I'm on a Mac 10.13..).

**Comment by Qirky** [comment]
Hi Joe, this is something that came to my attention recently so will aim at fixing today

**Comment by joesh1** [comment]
Just following the tutorial, so 'pluck' is the one I'm testing it with. I'll try it with something else later and get back to you if it's different.

**Comment by Qirky** [comment]
Figured it out - I recently changed "fmod" from just doing `freq = freq + fmod` to `freq = [freq, freq + fmod]` to flesh the sound out a bit but some SynthDefs do some more modulation of the frequency and causes it to expand out of an array of size 2 (stereo) which doesn't work with Pan2. Tbf I should probably look at expanding past 2 channels. Shouldn't take long to update any SynthDefs that have this issue

**Comment by Qirky** [comment]
This has been fixed in the latest commit and will hopefully go live later today on pypi
