### ISSUE TITLE
not saving

### ISSUE THREAD

**Issue by joesh1** [Qirky/FoxDot#83]
Hi

My code won't save, any suggestions? 

I've tried it a few times, but no luck.

Thanks in advance.

**Comment by Qirky** [comment]
Can you give me a little more info - do you get any error message in either the FoxDot console or your terminal window? Is it opening the save window at all? You're using MacOS correct? What's the content you are saving i.e. is it using special characters? Thanks

**Comment by joesh1** [comment]
Hi Ryan

Just to  make it simple, if I write `p1 >> play("= : ∞ + h d DD λ u u")` (as we discussed elsewhere), and then select save, or save as the file saves with the .py extension, but nothing in it! I did save a few pieces earlier, which is why it is a complete mystery that nothing is saving.
By the way, even if I try to save `p1 >> ("----")`, I still get the same problem.

**Comment by joesh1** [comment]
Hold on Ryan, I'll re-test several bits of code a little later (I'm still teaching), I'll have another go with some other code 'with' and without 'special characters' in, as that might make a difference!

**Comment by joesh1** [comment]
Hi Ryan, okay tested FD with the special characters, and indeed, if you have a special character you get a Unicode error -  

> UnicodeEncodeError: 'ascii' codec can't encode character u'\u03bb' in position 32: ordinal not in range(128)

However, what is a find a little odd is that if you include the lambda (λ) into the code it doesn't save, yet writing lambda does. 

Any thoughts?

**Comment by Qirky** [comment]
Ah it'll be because the λ gets replaced with "lambda" during the evaluation process - not when saving. I think I can just apply the same function to the text when saving and it should be ok.

**Comment by Qirky** [comment]
This has been fixed in the latest commit and will hopefully  go live later today on pypi
