### ISSUE TITLE
security of OSCFunc

### ISSUE THREAD

**Issue by claudeha** [Qirky/FoxDot#9]
There should be a warning in the getting started guide about

    msg[1].asString.interpret;  //will execute the string sent from python

because the OSCFunc can be triggered by anything with access to the port, and unixCmd exists in SC (so anything with access to the port can run arbitrary code on the system  as the user running SC).

Suggest using a strong firewall that blocks access from outside.

A strong TODO item should be figuring out a way to communicate with SC that doesn't go via network OSC, and so can't be injected.

**Comment by Qirky** [comment]
Hi Claude, SuperCollider now receives a filename of a local file that contains the SynthDef information and adds it to the server instead of interpreting SCLang code directly.
