### ISSUE TITLE
Transparency not erasing (Mac)

### ISSUE THREAD

**Issue by Chovin** [Qirky/FoxDot#91]
Just got around to testing Transparency.
Probably the same issue as https://github.com/Qirky/Troop/issues/7

![image](https://user-images.githubusercontent.com/17536161/36133504-1eb5549a-10ca-11e8-84a7-f9d9b7eaadbb.png)

![image](https://user-images.githubusercontent.com/17536161/36133497-0a844fbc-10ca-11e8-961a-702948c09567.png)

**Comment by Qirky** [comment]
I've added options in the config file called USE_ALPHA and ALPHA_VALUE that you can set to True and a value between 0 and 1. This will set the entire window (including text) to be semi-transparent. Not ideal but it's the only available workaround for your system I'm afraid.
