### ISSUE TITLE
invalid syntax during install

### ISSUE THREAD

**Issue by jwmatthys** [Qirky/FoxDot#95]
Installing from source on Ubuntu 17.10.

```
byte-compiling /usr/local/lib/python2.7/dist-packages/FoxDot/demo/13_advanced_clock.py to 13_advanced_clock.pyc
  File "/usr/local/lib/python2.7/dist-packages/FoxDot/demo/13_advanced_clock.py", line 19
    Clock.schedule(Clock.now() + 4, lambda: print("hello"))
                                                ^
SyntaxError: invalid syntax
```

**Comment by Qirky** [comment]
Hi what version of Python are you using? Are you getting this when installing using `python setup.py install` or are have you managed to install and get the error on startup? I've added a `from __future__` import to the file but it shouldn't get compiled as its package data on not a module. Let me know if this helps!

**Comment by jwmatthys** [comment]
I'm on Python 2.7.14. Your fix worked, thanks!

The error doesn't happen on a clean install but occurs when I pull the latest commits and re-run  ```python setup.py install```

So, if I ```rm -r /usr/lib/python2.7/dist-packages/FoxDox*``` and then run ```python setup.py install``` I have no problem.

But if I run ```python setup.py install``` again, it appears to attempt to compile the file and fails.

**Comment by Qirky** [comment]
What error does it fail with?

**Comment by jwmatthys** [comment]
Fixed
