### ISSUE TITLE
MIDI/Synth Timing Issues

### ISSUE THREAD

**Issue by TEZMan** [Qirky/FoxDot#97]
I've been trying to combine the use of the MIDI output controls and the Internal Synth/Player. When I do so, there is a very noticeable timing difference. In particular, the MIDI event fires about a half beat faster than does the player/synth event. I've tried adjusting with the nudge, and it does get it closer (using negative values) but when you start using negative values all the internal stuff starts to lose sync with each other. So at the least, I set the time to zero instead of 0.25, but it's still not entirely in sync. Basically, if I could get a value of the latency for the internal players/synth, and have a way to delay the MIDI out event by that precise amount, that would be dandy. I wouldn't doubt that could be in the code somewhere, and I've been looking, I just haven't found anything like that yet. (e.g. use the internal players to make a drum beat, and the external MIDI synth for a pad, keys, or whatever). 

I also noticed that if I use a PSum or any other function like rest() inside a player or instrument, it tends to eventually bail that instrument definition saying that recursion limit has been reached. If I set the PSum value to a var, then insert said var into the player it doesn't do that. I don't know if that's a bug or just something that happens, but just another quirk I noticed.

Biggest thing is the MIDI and Internal timing, if you could let me know how I can make that sync happen, that'd be great... BTW, I did try setting the sync_to_midi, and that didn't help, since the MIDI synth isn't sending a clock, it listens for a clock apparently (yes, python_rtmidi is installed). Again, let me know...  Thank you in advance.

**Comment by Qirky** [comment]
Hi there - I believe the issue is caused because music events in SuperCollider will have a timestamp and the midi events do not. I don't personally  use a midi device so this has sadly fallen low on the FoxDot todo list. I think it should be quite easy to add a `Clock.midi_nudge` value to delay the midi notes. I should probably also *attempt* to make them happen at the same time as I never updated the midi mechanics when I added the timestamp-ing to the OSC messages. 

As for the PSum big - can you give me an example of code that  throws the error?

**Comment by TEZMan** [comment]
The midi_nudge would be awesome... As far as the code that throws the
error, it's pretty much anything that uses a function, such as rest(),
PSum(), etc... It's not instant, it runs for a few minutes before throwing
the error and that synth stopping. I was running some live on Twitch today,
and the snare stopped in the middle of the track and I had to s1.stop()
then start it again to get a few more minutes of it playing... The only
thing in the pattern is "c1 >> MidiOut([-12], dur=[rest(),1], channel=4,
amp=.8) # Snare"...  It'll do the error regardless of whether it's MidiOut
or an internal synth... Just takes time for it to happen... Full error
below the sample code below, the code below takes a few (to several)
minutes to produce the error... It doesn't seem to be very consistent as to
when it will occur.

ch = var([0,3,5,4],[8,8,8,8]) # Major
b1 >> bass(ch, dur=PSum(6,4)) # Bass Internal Synth
y1 >> charm((ch,ch+2,ch+4,9), dur=PSum(3,4))

def vio():
    v1 >> viola(ch, dur=ch.dur, oct=(4,5)) + var([(0,2),(2,4)],[28,4])
    v2 >> viola(ch, dur=ch.dur, oct=(5,3)) + var([(0,2),(2,4)],[28,4])
vio()

d1 >> play("(x )(-[-x]-)", sample=4)
c1 >> play("  H ", sample=2, dur=2)
h1 >> play("s s( [ss])", sample=1)
s1 >> play(" (   O)O(    [ O])", sample=5)
t1 >> play("m  m  m( [ m])")


Traceback (most recent call last):
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\TempoClock.py",
line 345, in __run_block
    block.call(item)
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\TempoClock.py",
line 689, in call
    item()
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\TempoClock.py",
line 749, in __call__
    self.obj.__call__(*self.args, **self.kwargs)
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\Players.py",
line 656, in __call__
    self.metro.schedule(self, self.event_index, kwargs={})
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\TempoClock.py",
line 435, in schedule
    self.queue.add(obj, beat, args, kwargs)
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\TempoClock.py",
line 542, in add
    if beat < self.next():
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\Players.py",
line 2050, in __lt__
    return (self.dur < other)
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\Players.py",
line 2050, in __lt__
    return (self.dur < other)
  File
"C:\Users\Admin\AppData\Local\Programs\Python\Python36\lib\site-packages\FoxDot\lib\Players.py",
line 2050, in __lt__
    return (self.dur < other)
  [Previous line repeated 241 more times]
RecursionError: maximum recursion depth exceeded while calling a Python
object

**Comment by Qirky** [comment]
Hmm, I had the code running (inc. a line with a `rest()`) but was not able to reproduce the error. What version of FoxDot are you using? It should say in the title bar when you open the editor.

**Comment by TEZMan** [comment]
It did take a time for it to show, and the more things running the faster
it occurred. Anyway, FoxDot v0.5.14 is what I'm running...

**Comment by Qirky** [comment]
So I had a play with things again and I *did* manage to get the error when using `rest` and I think it's because when Players calculate their current "position" they add together their total duration a bunch of times and the `rest` objects weren't adding together properly. I believe I've fixed this and haven't been able to reproduce the error. If you update FoxDot, either from this repo or by running `pip install FoxDot --upgrade` in your command prompt, and let me know how you get on that'd be great.

**Comment by TEZMan** [comment]
Sure thing, I'll give it a try and let you know.

**Comment by TEZMan** [comment]
So far so good on the recursion message. 

As far as midi sync, let me know. A midi_nudge would be helpful at the least. But I’m sure I’m not the only one using midi. Let me know how I can help. As it stands currently, if I nudge the clock to 0.33 it’s exactly one beat off sync. I’m at 120bpm in the test project I’m playing with. 

Best Regards,
Matt

**Comment by Qirky** [comment]
So I've added midi timestamp-ing to the FoxDot Quark for SuperCollider. You'll need to update the Quark in SuperCollider - it's probably easiest to do by running:

`Quarks.gui`

In SuperCollider and updating. After this update the midi messages *should* be sent at the same time as FoxDot messages. If not, you can use the "delay" keyword to adjust when the midi messages are sent. If there are noticeable differences between midi and FoxDot sounds, I'll look a bit more in depth into adding a `midi_nudge` variable.

Let me know how you get on

**Comment by TEZMan** [comment]
Will do, I’ll let you know how it works. 

Best Regards,
Matt

**Comment by TEZMan** [comment]
did anything change to get midi messages out? I'm not getting any midi
messages at all to come out.

**Comment by TEZMan** [comment]
Here is what I use...

FoxDot.midi(2)

then

FoxDot.start()

Upon FoxDot.midi(2) it replies

MIDI: device 0 2 653482512  (Microsoft GS Wavetable Synth)
MIDI: device 1 3 653482520  (USB2.0-MIDI)
MIDI: device 2 4 653482528  (MIDIOUT2 (USB2.0-MIDI))
MIDI Sources:
    MIDIEndPoint("USB2.0-MIDI", "USB2.0-MIDI")
MIDI Destinations:
    MIDIEndPoint("Microsoft GS Wavetable Synth", "Microsoft GS Wavetable
Synth")
    MIDIEndPoint("USB2.0-MIDI", "USB2.0-MIDI")
    MIDIEndPoint("MIDIOUT2 (USB2.0-MIDI)", "MIDIOUT2 (USB2.0-MIDI)")
Sending FoxDot MIDI messages to MIDIOUT2 (USB2.0-MIDI)

I then run FoxDot.start()

then from FoxDot I run

ch = var([0,3,5,4],[8,8,8,8]) # Major
b1 >> MidiOut((ch-7,ch,ch+2,ch+4), dur=8, sus=8, channel=5, amp=.6,
scale=Scale.major) # Choir MIDI

The midi adapter works fine in Ableton just in FoxDot it's not sending
messages via MIDI now... It did prior to updating the quark... If I let it
run a while it will eventually start replying with "scheduler queue is
full." messages.

On the USB MIDI adapter I have, it has an activity indicator LED, and that
is not currently activating at all. I even uninstalled the quark and
reinstalled it to see if that helped..

**Comment by TEZMan** [comment]
Ok, so the pip install --upgrade command was still looking at 0.6.1, so I
manually grabbed the github version and it works on 0.6.2... I set the
MidiOut delay to 0.43 and it seems to be in sync... I attached a quick
output of the test... The MIDI snare is on 1 so you can hear the timing
working... 0 delay, 0.25 would be the same as the default Clock.latency,
still slightly off, then adjusted to 0.43 seems to be spot on... You can
see the delay more if you load it in audacity to visually see the delay...
Let me know if you need any help testing...

**Comment by Qirky** [comment]
Hmm I can't seem to see the attachment but you're saying that you still need to add a delay to the `MidiOut` player? Once you've set the delay, it's ok though? There's no drift in and out of time?

**Comment by TEZMan** [comment]
Apparently MP3 files aren't supported as direct attachments, so I zipped them all up and attached them... 
I hadn't let it run a long time to see if it stays in sync, but I've been letting it run the last 5 minutes and so far it's stayed in sync... But I don't have it loaded with a ton of activity right now, just the MidiOut and a play() function... Is there a specific test you'd like me to try? Below is what I'm using to test... Or a slight variation of it, meaning the Midi notes may be different from the MP3, but it's the same commands.

c1 >> MidiOut([-20,-21,-28,-26], dur=1, channel=4, delay=MidiDelay, scale=Scale.chromatic)
d1 >> play("1234",dur=1)

[MP3s.zip](https://github.com/Qirky/FoxDot/files/1942900/MP3s.zip)

**Comment by TEZMan** [comment]
I've added a track I just did... Now, one reason I mention to use the drums from play() rather than midi, is that if I get too much Midi activity I will notice Midi drift... The drums being a big portion of the Midi activity if I'm using them over the Midi... I think I had 6 or 7 Midi tracks running, but when I added the next it started to drift from the other Midi timings, not necessarily drifting from the main clock, just that the timing in general of the notes... So the Midi played notes may be off from each other.. For example... Midi note 1 may be played on time, but midi note 2 might be a few (30-40) milliseconds late in hitting, then 3 might be only 10ms late, and 4 might be on time... It seems to depend on how much midi activity is going on... I figure that might just be a limitation of Midi in general, but it may be related to the way it iterates over the tracks too... But in general, I try to limit too much Midi activity to hopefully reduce that... Anyway, this might be completely off topic, but let me know if anything I rambled on about is useful and/or makes any sense... LOL 

[multitrack.zip](https://github.com/Qirky/FoxDot/files/1943043/multitrack.zip)

**Comment by Qirky** [comment]
Yeah it doesn't seem to be in sync does it? I'm having a friend bring an external midi device round this weekend so I can test it out. I'll let you know how I get on

**Comment by Qirky** [comment]
Hey, so if you upgrade FoxDot (either via pip or from this repo) and the Quark again you should be able to use `Clock.midi_nudge` which you can adjust to sync ext. midi and FoxDot events. I found a value of around 0.175 worked for me but it'll probably vary system to system. Let me know how you get on!
