### ISSUE TITLE
duplicate line shortcut in IDE

### ISSUE THREAD

**Issue by Almenon** [Qirky/FoxDot#99]
It would be cool if there was a duplicate line shortcut in the IDE.  I was guiding a beginner through foxdot and she mentioned that she was dissapointed that it didn't have a duplicate line command like Pycharm.

**Comment by Qirky** [comment]
Does it just insert a copy of the current line on the line below? What is the keyboard shortcut used in Pycharm?

**Comment by Qirky** [comment]
Ctrl+D now duplicates a line of text

**Comment by Almenon** [comment]
Oh dang, just realized I never answered your question.  Thanks anyways.
